-- Permanently remove demo/seed listings that were not created by a user.
--
-- Seed listings use the 'lst-seed-*' id prefix (previously generated by
-- js/app.js seedListings()). They are now removed from the shared catalog
-- and stripped from every user's local app_state payload so they never
-- reappear. listing_images, saved_listings, and listing_inquiries rows
-- referencing these ids are deleted automatically (on delete cascade).
--
-- Run this once in the Supabase SQL Editor.

-- Preview the rows that will be removed:
select id, ref, title, status, owner_id
from public.shared_listings
where id like 'lst-seed-%'
order by id;

begin;

-- 1) Remove seed listings from the shared catalog (cascades to related rows).
delete from public.shared_listings
where id like 'lst-seed-%';

-- 2) Strip seed listings from each user's local app_state payload.
update public.app_state a
set payload = jsonb_set(
  a.payload,
  '{listings}',
  coalesce(
    (
      select jsonb_agg(item)
      from jsonb_array_elements(
        case when jsonb_typeof(a.payload -> 'listings') = 'array'
             then a.payload -> 'listings' else '[]'::jsonb end
      ) as item
      where item ->> 'id' not like 'lst-seed-%'
    ),
    '[]'::jsonb
  ),
  true
)
where exists (
  select 1
  from jsonb_array_elements(
    case when jsonb_typeof(a.payload -> 'listings') = 'array'
         then a.payload -> 'listings' else '[]'::jsonb end
  ) as item
  where item ->> 'id' like 'lst-seed-%'
);

-- 3) Drop any leftover listingStats entries for seed listings.
do $$
declare
  r record;
  seed_key text;
  new_stats jsonb;
begin
  for r in
    select id, payload
    from public.app_state
    where payload ? 'listingStats'
      and jsonb_typeof(payload -> 'listingStats') = 'object'
  loop
    new_stats := r.payload -> 'listingStats';
    for seed_key in
      select k
      from jsonb_object_keys(new_stats) as k
      where k like 'lst-seed-%'
    loop
      new_stats := new_stats - seed_key;
    end loop;
    if new_stats <> (r.payload -> 'listingStats') then
      update public.app_state
      set payload = jsonb_set(r.payload, '{listingStats}', new_stats)
      where id = r.id;
    end if;
  end loop;
end;
$$;

commit;

-- Verify nothing is left behind:
select count(*) as remaining_seed_listings
from public.shared_listings
where id like 'lst-seed-%';
