-- Shared listing catalog and inventory for every authenticated role.
-- All roles can view. Brokers and agents can publish. Only the listing owner
-- (or Super Admin) can edit/delete. Safe to re-run.

create table if not exists public.shared_listings (
  id text primary key,
  ref text not null default '',
  title text not null default '',
  status text not null default 'available',
  payload jsonb not null default '{}'::jsonb,
  owner_id uuid not null references auth.users(id) on delete cascade,
  views bigint not null default 0,
  inquiries bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shared_listings_payload_object check (jsonb_typeof(payload) = 'object')
);

create index if not exists shared_listings_owner_id_idx on public.shared_listings (owner_id);
create index if not exists shared_listings_status_idx on public.shared_listings (status);
create index if not exists shared_listings_updated_at_idx on public.shared_listings (updated_at desc);

-- Import existing broker/agent/admin listings. Duplicate sample IDs are
-- imported once, while generated real listing IDs remain unchanged.
-- Demo/seed listings (ids like 'lst-seed-*', generated by the old
-- js/app.js seedListings()) are skipped so they can never be re-imported.
with existing as (
  select distinct on (listing.item ->> 'id')
    listing.item,
    a.owner_id,
    coalesce((a.payload -> 'listingStats' -> (listing.item ->> 'id') ->> 'views')::bigint, 0) as views,
    coalesce((a.payload -> 'listingStats' -> (listing.item ->> 'id') ->> 'inquiries')::bigint, 0) as inquiries
  from public.app_state a
  join public.profiles p on p.id = a.owner_id and p.role in ('super-admin', 'broker', 'agent')
  cross join lateral jsonb_array_elements(
    case when jsonb_typeof(a.payload -> 'listings') = 'array' then a.payload -> 'listings' else '[]'::jsonb end
  ) as listing(item)
  where coalesce(listing.item ->> 'id', '') <> ''
    and listing.item ->> 'id' not like 'lst-seed-%'
  order by listing.item ->> 'id',
    case p.role when 'broker' then 1 when 'agent' then 2 else 3 end,
    a.owner_id
)
insert into public.shared_listings (id, ref, title, status, payload, owner_id, views, inquiries)
select
  item ->> 'id',
  coalesce(item ->> 'ref', ''),
  coalesce(item ->> 'title', ''),
  coalesce(item ->> 'status', 'available'),
  item || jsonb_build_object('createdBy', owner_id::text),
  owner_id,
  views,
  inquiries
from existing
on conflict (id) do nothing;

alter table public.shared_listings enable row level security;

drop policy if exists "shared_listings authenticated read" on public.shared_listings;
drop policy if exists "shared_listings owner internal read" on public.shared_listings;
drop policy if exists "shared_listings publisher insert" on public.shared_listings;
drop policy if exists "shared_listings owner update" on public.shared_listings;
drop policy if exists "shared_listings owner delete" on public.shared_listings;

create or replace function public.listing_current_user_is_approved()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles me
    where me.id = auth.uid() and me.registration_status = 'approved'
  );
$$;

create or replace function public.listing_current_user_can_publish()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles me
    where me.id = auth.uid()
      and me.role in ('broker', 'agent')
      and me.registration_status = 'approved'
  );
$$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'shared_listings'
      and column_name = 'is_published'
  ) then
    create policy "shared_listings owner internal read"
      on public.shared_listings for select
      using (public.is_super_admin() or (
        owner_id = auth.uid() and public.listing_current_user_can_publish()
      ));
  else
    create policy "shared_listings authenticated read"
      on public.shared_listings for select
      using (public.listing_current_user_is_approved());
  end if;
end;
$$;

create policy "shared_listings publisher insert"
  on public.shared_listings for insert
  with check (
    public.is_super_admin()
    or (owner_id = auth.uid() and public.listing_current_user_can_publish())
  );

create policy "shared_listings owner update"
  on public.shared_listings for update
  using (public.is_super_admin() or (owner_id = auth.uid() and public.listing_current_user_can_publish()))
  with check (public.is_super_admin() or (owner_id = auth.uid() and public.listing_current_user_can_publish()));

create policy "shared_listings owner delete"
  on public.shared_listings for delete
  using (public.is_super_admin() or (owner_id = auth.uid() and public.listing_current_user_can_publish()));

-- Authenticated viewers can increment aggregate listing analytics without
-- receiving update permission on the listing itself.
create or replace function public.increment_shared_listing_stat(p_listing_id text, p_stat text)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.listing_current_user_is_approved() then raise exception 'Approved account required'; end if;
  if p_stat = 'views' then
    update public.shared_listings set views = views + 1 where id = p_listing_id;
  elsif p_stat = 'inquiries' then
    update public.shared_listings set inquiries = inquiries + 1 where id = p_listing_id;
  else
    raise exception 'Unsupported listing statistic';
  end if;
end;
$$;

revoke all on function public.listing_current_user_can_publish() from public;
grant execute on function public.listing_current_user_can_publish() to authenticated;
revoke all on function public.listing_current_user_is_approved() from public;
grant execute on function public.listing_current_user_is_approved() to authenticated;
revoke all on function public.increment_shared_listing_stat(text, text) from public;
do $$
begin
  grant select, insert, update, delete on public.shared_listings to authenticated;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'shared_listings'
      and column_name = 'is_published'
  ) then
    revoke insert, update, delete on public.shared_listings from authenticated;
    revoke execute on function public.increment_shared_listing_stat(text, text) from authenticated;
  else
    grant execute on function public.increment_shared_listing_stat(text, text) to authenticated;
  end if;
end;
$$;

notify pgrst, 'reload schema';

select
  tablename,
  has_table_privilege('authenticated', 'public.shared_listings', 'select') as can_select,
  has_table_privilege('authenticated', 'public.shared_listings', 'insert') as can_insert,
  has_table_privilege('authenticated', 'public.shared_listings', 'update') as can_update,
  has_table_privilege('authenticated', 'public.shared_listings', 'delete') as can_delete
from pg_tables
where schemaname = 'public' and tablename = 'shared_listings';
