"use strict";
/* Philippines region -> province -> city/municipality lookup.
 *
 * GENERATED from the PH_GEO table in js/app.js by tools/gen_ph_geo.js - do not
 * edit by hand. Run `node tools/gen_ph_geo.js --check` to confirm it is current.
 *
 * This exists because liveBenchmarkListings() could only filter on `city`. For a
 * province-only query it had nothing to match on and emitted a median row for
 * every city the worker had ever seen, so a "Metro Manila" scan came back with
 * Padre Garcia (Batangas), Calamba (Laguna) and Bagac (Bataan) in it. The rows
 * carried a real city; nothing was ever checking which province it was in.
 *
 * Lookups are case- and punctuation-insensitive, so "lapu-lapu" and
 * "Lapu-Lapu" agree.
 */

const PROVINCE_CITIES = {
  "Metro Manila": [
    "Caloocan",
    "Las Piñas",
    "Makati",
    "Malabon",
    "Mandaluyong",
    "Manila",
    "Marikina",
    "Muntinlupa",
    "Navotas",
    "Parañaque",
    "Pasay",
    "Pasig",
    "Pateros",
    "Quezon City",
    "San Juan",
    "Taguig",
    "Valenzuela"
  ],
  "Abra": [
    "Bangued",
    "Boliney",
    "Bucay",
    "Bucloc",
    "Daguioman",
    "Danglas",
    "Dolores",
    "La Paz",
    "Lacub",
    "Lagangilang",
    "Lagayan",
    "Langiden",
    "Licuan-Baay",
    "Luba",
    "Malibcong",
    "Manabo",
    "Peñarrubia",
    "Pidigan",
    "Pilar",
    "Sallapadan",
    "San Isidro",
    "San Juan",
    "San Quintin",
    "Tayum",
    "Tineg",
    "Tubo",
    "Villaviciosa"
  ],
  "Apayao": [
    "Calanasan",
    "Conner",
    "Flora",
    "Kabugao",
    "Luna",
    "Pudtol",
    "Santa Marcela"
  ],
  "Benguet": [
    "Atok",
    "Baguio",
    "Bakun",
    "Bokod",
    "Buguias",
    "Itogon",
    "Kabayan",
    "Kapangan",
    "Kibungan",
    "La Trinidad",
    "Mankayan",
    "Sablan",
    "Tuba",
    "Tublay"
  ],
  "Ifugao": [
    "Aguinaldo",
    "Alfonso Lista",
    "Asipulo",
    "Banaue",
    "Hingyon",
    "Hungduan",
    "Kiangan",
    "Lagawe",
    "Lamut",
    "Mayoyao",
    "Tinoc"
  ],
  "Kalinga": [
    "Balbalan",
    "Lubuagan",
    "Pasil",
    "Pinukpuk",
    "Rizal",
    "Tabuk",
    "Tanudan",
    "Tinglayan"
  ],
  "Mountain Province": [
    "Barlig",
    "Bauko",
    "Besao",
    "Bontoc",
    "Natonin",
    "Paracelis",
    "Sabangan",
    "Sadanga",
    "Sagada",
    "Tadian"
  ],
  "Ilocos Norte": [
    "Adams",
    "Bacarra",
    "Badoc",
    "Bangui",
    "Banna",
    "Batac",
    "Burgos",
    "Carasi",
    "Currimao",
    "Dingras",
    "Dumalneg",
    "Laoag",
    "Marcos",
    "Nueva Era",
    "Pagudpud",
    "Paoay",
    "Pasuquin",
    "Piddig",
    "Pinili",
    "San Nicolas",
    "Sarrat",
    "Solsona",
    "Vintar"
  ],
  "Ilocos Sur": [
    "Alilem",
    "Banayoyo",
    "Bantay",
    "Burgos",
    "Cabugao",
    "Candon",
    "Caoayan",
    "Cervantes",
    "Galimuyod",
    "Gregorio del Pilar",
    "Lidlidda",
    "Magsingal",
    "Nagbukel",
    "Narvacan",
    "Quirino",
    "Salcedo",
    "San Emilio",
    "San Esteban",
    "San Ildefonso",
    "San Juan",
    "San Vicente",
    "Santa",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Domingo",
    "Sigay",
    "Sinait",
    "Sugpon",
    "Suyo",
    "Tagudin",
    "Vigan"
  ],
  "La Union": [
    "Agoo",
    "Aringay",
    "Bacnotan",
    "Bagulin",
    "Balaoan",
    "Bangar",
    "Bauang",
    "Burgos",
    "Caba",
    "Luna",
    "Naguilian",
    "Pugo",
    "Rosario",
    "San Fernando",
    "San Gabriel",
    "San Juan",
    "San Vicente",
    "Santol",
    "Santo Tomas",
    "Sudipen",
    "Tubao"
  ],
  "Pangasinan": [
    "Agno",
    "Aguilar",
    "Alaminos",
    "Alcala",
    "Anda",
    "Asingan",
    "Balungao",
    "Bani",
    "Basista",
    "Bautista",
    "Bayambang",
    "Binalonan",
    "Binmaley",
    "Bolinao",
    "Bugallon",
    "Burgos",
    "Calasiao",
    "Dagupan",
    "Dasol",
    "Infanta",
    "Labrador",
    "Laoac",
    "Lingayen",
    "Mabini",
    "Malasiqui",
    "Manaoag",
    "Mangaldan",
    "Mangatarem",
    "Mapandan",
    "Natividad",
    "Pozorrubio",
    "Rosales",
    "San Carlos",
    "San Fabian",
    "San Jacinto",
    "San Manuel",
    "San Nicolas",
    "San Quintin",
    "Santa Barbara",
    "Santa Maria",
    "Santo Tomas",
    "Sison",
    "Sual",
    "Tayug",
    "Umingan",
    "Urbiztondo",
    "Urdaneta",
    "Villasis"
  ],
  "Batanes": [
    "Basco",
    "Itbayat",
    "Ivana",
    "Mahatao",
    "Sabtang",
    "Uyugan"
  ],
  "Cagayan": [
    "Abulug",
    "Alcala",
    "Allacapan",
    "Amulung",
    "Aparri",
    "Baggao",
    "Ballesteros",
    "Buguey",
    "Calayan",
    "Camalaniugan",
    "Claveria",
    "Enrile",
    "Gattaran",
    "Gonzaga",
    "Iguig",
    "Lal-lo",
    "Lasam",
    "Pamplona",
    "Peñablanca",
    "Piat",
    "Rizal",
    "Sanchez-Mira",
    "Santa Ana",
    "Santa Praxedes",
    "Santa Teresita",
    "Santo Niño",
    "Solana",
    "Tuao",
    "Tuguegarao"
  ],
  "Isabela": [
    "Alicia",
    "Angadanan",
    "Aurora",
    "Benito Soliven",
    "Burgos",
    "Cabagan",
    "Cabatuan",
    "Cauayan",
    "Cordon",
    "Delfin Albano",
    "Dinapigue",
    "Divilacan",
    "Echague",
    "Gamu",
    "Ilagan",
    "Jones",
    "Luna",
    "Maconacon",
    "Mallig",
    "Naguilian",
    "Palanan",
    "Quezon",
    "Quirino",
    "Ramon",
    "Reina Mercedes",
    "Roxas",
    "San Agustin",
    "San Guillermo",
    "San Isidro",
    "San Manuel",
    "San Mariano",
    "San Mateo",
    "San Pablo",
    "Santa Maria",
    "Santiago",
    "Santo Tomas",
    "Tumauini"
  ],
  "Nueva Vizcaya": [
    "Alfonso Castañeda",
    "Ambaguio",
    "Aritao",
    "Bagabag",
    "Bambang",
    "Bayombong",
    "Diadi",
    "Dupax del Norte",
    "Dupax del Sur",
    "Kasibu",
    "Kayapa",
    "Quezon",
    "Santa Fe",
    "Solano",
    "Villaverde"
  ],
  "Quirino": [
    "Aglipay",
    "Cabarroguis",
    "Diffun",
    "Maddela",
    "Nagtipunan",
    "Saguday"
  ],
  "Aurora": [
    "Baler",
    "Casiguran",
    "Dilasag",
    "Dinalungan",
    "Dingalan",
    "Dipaculao",
    "Maria Aurora",
    "San Luis"
  ],
  "Bataan": [
    "Abucay",
    "Bagac",
    "Balanga",
    "Dinalupihan",
    "Hermosa",
    "Limay",
    "Mariveles",
    "Morong",
    "Orani",
    "Orion",
    "Pilar",
    "Samal"
  ],
  "Bulacan": [
    "Angat",
    "Balagtas",
    "Baliuag",
    "Bocaue",
    "Bulakan",
    "Bustos",
    "Calumpit",
    "Doña Remedios Trinidad",
    "Guiguinto",
    "Hagonoy",
    "Malolos",
    "Marilao",
    "Meycauayan",
    "Norzagaray",
    "Obando",
    "Pandi",
    "Paombong",
    "Plaridel",
    "Pulilan",
    "San Ildefonso",
    "San Jose del Monte",
    "San Miguel",
    "San Rafael",
    "Santa Maria"
  ],
  "Nueva Ecija": [
    "Aliaga",
    "Bongabon",
    "Cabiao",
    "Cabanatuan",
    "Carranglan",
    "Cuyapo",
    "Gabaldon",
    "Gapan",
    "General Mamerto Natividad",
    "General Tinio",
    "Guimba",
    "Jaen",
    "Laur",
    "Licab",
    "Llanera",
    "Lupao",
    "Muñoz",
    "Nampicuan",
    "Palayan",
    "Pantabangan",
    "Peñaranda",
    "Quezon",
    "Rizal",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Leonardo",
    "Santa Rosa",
    "Santo Domingo",
    "Talavera",
    "Talugtug",
    "Zaragoza"
  ],
  "Pampanga": [
    "Angeles",
    "Apalit",
    "Arayat",
    "Bacolor",
    "Candaba",
    "Floridablanca",
    "Guagua",
    "Lubao",
    "Mabalacat",
    "Macabebe",
    "Magalang",
    "Masantol",
    "Mexico",
    "Minalin",
    "Porac",
    "San Fernando",
    "San Luis",
    "San Simon",
    "Santa Ana",
    "Santa Rita",
    "Santo Tomas",
    "Sasmuan"
  ],
  "Tarlac": [
    "Anao",
    "Bamban",
    "Camiling",
    "Capas",
    "Concepcion",
    "Gerona",
    "La Paz",
    "Mayantoc",
    "Moncada",
    "Paniqui",
    "Pura",
    "Ramos",
    "San Clemente",
    "San Jose",
    "San Manuel",
    "Santa Ignacia",
    "Tarlac City",
    "Victoria"
  ],
  "Zambales": [
    "Botolan",
    "Cabangan",
    "Candelaria",
    "Castillejos",
    "Iba",
    "Masinloc",
    "Olongapo",
    "Palauig",
    "San Antonio",
    "San Felipe",
    "San Marcelino",
    "San Narciso",
    "San Salvador",
    "Subic"
  ],
  "Batangas": [
    "Agoncillo",
    "Alitagtag",
    "Balayan",
    "Balete",
    "Batangas City",
    "Bauan",
    "Calaca",
    "Calatagan",
    "Cuenca",
    "Ibaan",
    "Laurel",
    "Lemery",
    "Lian",
    "Lipa",
    "Lobo",
    "Mabini",
    "Malvar",
    "Mataasnakahoy",
    "Nasugbu",
    "Padre Garcia",
    "Rosario",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Nicolas",
    "San Pascual",
    "Santa Teresita",
    "Santo Tomas",
    "Taal",
    "Talisay",
    "Tanauan",
    "Taysan",
    "Tingloy",
    "Tuy"
  ],
  "Cavite": [
    "Alfonso",
    "Amadeo",
    "Bacoor",
    "Carmona",
    "Cavite City",
    "Dasmariñas",
    "General Emilio Aguinaldo",
    "General Mariano Alvarez",
    "General Trias",
    "Imus",
    "Indang",
    "Kawit",
    "Magallanes",
    "Maragondon",
    "Mendez",
    "Naic",
    "Noveleta",
    "Rosario",
    "Silang",
    "Tagaytay",
    "Tanza",
    "Ternate",
    "Trece Martires"
  ],
  "Laguna": [
    "Alaminos",
    "Bay",
    "Biñan",
    "Cabuyao",
    "Calamba",
    "Calauan",
    "Cavinti",
    "Famy",
    "Kalayaan",
    "Liliw",
    "Los Baños",
    "Luisiana",
    "Lumban",
    "Mabitac",
    "Magdalena",
    "Majayjay",
    "Nagcarlan",
    "Paete",
    "Pagsanjan",
    "Pakil",
    "Pangil",
    "Pila",
    "Rizal",
    "San Pablo",
    "San Pedro",
    "Santa Cruz",
    "Santa Maria",
    "Santa Rosa",
    "Siniloan",
    "Victoria"
  ],
  "Quezon": [
    "Agdangan",
    "Alabat",
    "Atimonan",
    "Buenavista",
    "Burdeos",
    "Calauag",
    "Candelaria",
    "Catanauan",
    "Dolores",
    "General Luna",
    "General Nakar",
    "Guinayangan",
    "Gumaca",
    "Infanta",
    "Jomalig",
    "Lopez",
    "Lucban",
    "Lucena",
    "Macalelon",
    "Mauban",
    "Mulanay",
    "Padre Burgos",
    "Pagbilao",
    "Panukulan",
    "Patnanungan",
    "Perez",
    "Pitogo",
    "Plaridel",
    "Polillo",
    "Quezon",
    "Real",
    "Sampaloc",
    "San Andres",
    "San Antonio",
    "San Francisco",
    "San Narciso",
    "Sariaya",
    "Tagkawayan",
    "Tayabas",
    "Tiaong",
    "Unisan"
  ],
  "Rizal": [
    "Angono",
    "Antipolo",
    "Baras",
    "Binangonan",
    "Cainta",
    "Cardona",
    "Jalajala",
    "Morong",
    "Pililla",
    "Rodriguez",
    "San Mateo",
    "Tanay",
    "Taytay",
    "Teresa"
  ],
  "Marinduque": [
    "Boac",
    "Buenavista",
    "Gasan",
    "Mogpog",
    "Santa Cruz",
    "Torrijos"
  ],
  "Occidental Mindoro": [
    "Abra de Ilog",
    "Calintaan",
    "Looc",
    "Lubang",
    "Magsaysay",
    "Mamburao",
    "Paluan",
    "Rizal",
    "Sablayan",
    "San Jose",
    "Santa Cruz"
  ],
  "Oriental Mindoro": [
    "Baco",
    "Bansud",
    "Bongabong",
    "Bulalacao",
    "Calapan",
    "Gloria",
    "Mansalay",
    "Naujan",
    "Pinamalayan",
    "Pola",
    "Puerto Galera",
    "Roxas",
    "San Teodoro",
    "Socorro",
    "Victoria"
  ],
  "Palawan": [
    "Aborlan",
    "Agutaya",
    "Araceli",
    "Balabac",
    "Bataraza",
    "Brooke's Point",
    "Busuanga",
    "Cagayancillo",
    "Coron",
    "Culion",
    "Cuyo",
    "Dumaran",
    "El Nido",
    "Kalayaan",
    "Linapacan",
    "Magsaysay",
    "Narra",
    "Puerto Princesa",
    "Quezon",
    "Rizal",
    "Roxas",
    "San Vicente",
    "Sofronio Española",
    "Taytay"
  ],
  "Romblon": [
    "Alcantara",
    "Banton",
    "Cajidiocan",
    "Calatrava",
    "Concepcion",
    "Corcuera",
    "Ferrol",
    "Looc",
    "Magdiwang",
    "Odiongan",
    "Romblon",
    "San Agustin",
    "San Andres",
    "San Fernando",
    "San Jose",
    "Santa Fe",
    "Santa Maria",
    "Sibuyan"
  ],
  "Albay": [
    "Bacacay",
    "Camalig",
    "Daraga",
    "Guinobatan",
    "Jovellar",
    "Legazpi",
    "Libon",
    "Ligao",
    "Malilipot",
    "Malinao",
    "Manito",
    "Oas",
    "Pio Duran",
    "Polangui",
    "Rapu-Rapu",
    "Santo Domingo",
    "Tabaco",
    "Tiwi"
  ],
  "Camarines Norte": [
    "Basud",
    "Capalonga",
    "Daet",
    "Jose Panganiban",
    "Labo",
    "Mercedes",
    "Paracale",
    "San Lorenzo Ruiz",
    "San Vicente",
    "Santa Elena",
    "Talisay",
    "Vinzons"
  ],
  "Camarines Sur": [
    "Baao",
    "Balatan",
    "Bato",
    "Bombon",
    "Buhi",
    "Bula",
    "Cabusao",
    "Calabanga",
    "Camaligan",
    "Canaman",
    "Caramoan",
    "Del Gallego",
    "Gainza",
    "Garchitorena",
    "Goa",
    "Iriga",
    "Lagonoy",
    "Libmanan",
    "Lupi",
    "Magarao",
    "Milaor",
    "Minalabac",
    "Nabua",
    "Naga",
    "Ocampo",
    "Pamplona",
    "Pasacao",
    "Pili",
    "Presentacion",
    "Ragay",
    "Sagñay",
    "San Fernando",
    "San Jose",
    "Sipocot",
    "Siruma",
    "Tigaon",
    "Tinambac"
  ],
  "Catanduanes": [
    "Bagamanoc",
    "Baras",
    "Bato",
    "Caramoran",
    "Gigmoto",
    "Pandan",
    "Panganiban",
    "San Andres",
    "San Miguel",
    "Viga",
    "Virac"
  ],
  "Masbate": [
    "Aroroy",
    "Baleno",
    "Balud",
    "Batuan",
    "Cataingan",
    "Cawayan",
    "Claveria",
    "Dimasalang",
    "Esperanza",
    "Mandaon",
    "Masbate City",
    "Mobo",
    "Monreal",
    "Palanas",
    "Pio V. Corpuz",
    "Placer",
    "San Fernando",
    "San Jacinto",
    "San Pascual",
    "Uson"
  ],
  "Sorsogon": [
    "Barcelona",
    "Bulan",
    "Bulusan",
    "Casiguran",
    "Castilla",
    "Donsol",
    "Gubat",
    "Irosin",
    "Juban",
    "Magallanes",
    "Matnog",
    "Pilar",
    "Prieto Diaz",
    "Santa Magdalena",
    "Sorsogon City"
  ],
  "Aklan": [
    "Altavas",
    "Balete",
    "Banga",
    "Batan",
    "Buruanga",
    "Ibajay",
    "Kalibo",
    "Lezo",
    "Libacao",
    "Madalag",
    "Makato",
    "Malay",
    "Malinao",
    "Nabas",
    "New Washington",
    "Numancia",
    "Tangalan"
  ],
  "Antique": [
    "Anini-y",
    "Barbaza",
    "Belison",
    "Bugasong",
    "Caluya",
    "Culasi",
    "Hamtic",
    "Laua-an",
    "Libertad",
    "Pandan",
    "Patnongon",
    "San Jose de Buenavista",
    "San Remigio",
    "Sebaste",
    "Sibalom",
    "Tibiao",
    "Tobias Fornier",
    "Valderrama"
  ],
  "Capiz": [
    "Cuartero",
    "Dao",
    "Dumalag",
    "Dumarao",
    "Ivisan",
    "Jamindan",
    "Ma-ayon",
    "Mambusao",
    "Panay",
    "Panitan",
    "Pilar",
    "Pontevedra",
    "President Roxas",
    "Roxas",
    "Sapian",
    "Sigma",
    "Tapaz"
  ],
  "Guimaras": [
    "Buenavista",
    "Jordan",
    "Nueva Valencia",
    "San Lorenzo",
    "Sibunag"
  ],
  "Iloilo": [
    "Ajuy",
    "Alimodian",
    "Anilao",
    "Badiangan",
    "Balasan",
    "Banate",
    "Barotac Nuevo",
    "Barotac Viejo",
    "Batad",
    "Bingawan",
    "Cabatuan",
    "Calinog",
    "Carles",
    "Concepcion",
    "Dingle",
    "Dueñas",
    "Dumangas",
    "Estancia",
    "Guimbal",
    "Igbaras",
    "Iloilo City",
    "Janiuay",
    "Lambunao",
    "Leganes",
    "Lemery",
    "Leon",
    "Maasin",
    "Miagao",
    "Mina",
    "New Lucena",
    "Oton",
    "Passi",
    "Pavia",
    "Pototan",
    "San Dionisio",
    "San Enrique",
    "San Joaquin",
    "San Miguel",
    "San Rafael",
    "Santa Barbara",
    "Sara",
    "Tigbauan",
    "Tubungan",
    "Zarraga"
  ],
  "Negros Occidental": [
    "Bago",
    "Binalbagan",
    "Cadiz",
    "Calatrava",
    "Candoni",
    "Cauayan",
    "Enrique B. Magalona",
    "Escalante",
    "Himamaylan",
    "Hinigaran",
    "Hinoba-an",
    "Ilog",
    "Isabela",
    "Kabankalan",
    "La Carlota",
    "La Castellana",
    "Manapla",
    "Moises Padilla",
    "Murcia",
    "Pontevedra",
    "Pulupandan",
    "Sagay",
    "Salvador Benedicto",
    "San Carlos",
    "San Enrique",
    "Silay",
    "Sipalay",
    "Talisay",
    "Toboso",
    "Valladolid",
    "Victorias"
  ],
  "Bohol": [
    "Alburquerque",
    "Alicia",
    "Anda",
    "Antequera",
    "Baclayon",
    "Balilihan",
    "Batuan",
    "Bien Unido",
    "Bilar",
    "Buenavista",
    "Calape",
    "Candijay",
    "Carmen",
    "Catigbian",
    "Clarin",
    "Corella",
    "Cortes",
    "Dagohoy",
    "Danao",
    "Dauis",
    "Dimiao",
    "Duero",
    "Garcia Hernandez",
    "Getafe",
    "Guindulman",
    "Inabanga",
    "Jagna",
    "Lila",
    "Loay",
    "Loboc",
    "Loon",
    "Mabini",
    "Maribojoc",
    "Panglao",
    "Pilar",
    "President Carlos P. Garcia",
    "Sagbayan",
    "San Isidro",
    "San Miguel",
    "Sevilla",
    "Sierra Bullones",
    "Sikatuna",
    "Tagbilaran",
    "Talibon",
    "Trinidad",
    "Tubigon",
    "Ubay",
    "Valencia"
  ],
  "Cebu": [
    "Alcantara",
    "Alcoy",
    "Alegria",
    "Aloguinsan",
    "Argao",
    "Asturias",
    "Badian",
    "Balamban",
    "Bantayan",
    "Barili",
    "Bogo",
    "Boljoon",
    "Borbon",
    "Carcar",
    "Carmen",
    "Catmon",
    "Cebu City",
    "Compostela",
    "Consolacion",
    "Cordova",
    "Daanbantayan",
    "Dalaguete",
    "Dumanjug",
    "Ginatilan",
    "Liloan",
    "Madridejos",
    "Malabuyoc",
    "Mandaue",
    "Medellin",
    "Minglanilla",
    "Moalboal",
    "Naga",
    "Oslob",
    "Pilar",
    "Pinamungajan",
    "Poro",
    "Ronda",
    "Samboan",
    "San Fernando",
    "San Francisco",
    "San Remigio",
    "Santa Fe",
    "Santander",
    "Sibonga",
    "Sogod",
    "Tabogon",
    "Tabuelan",
    "Talisay",
    "Toledo",
    "Tuburan",
    "Tudela"
  ],
  "Negros Oriental": [
    "Amlan",
    "Ayungon",
    "Bacong",
    "Bais",
    "Basay",
    "Bayawan",
    "Bindoy",
    "Dauin",
    "Dumaguete",
    "Guihulngan",
    "Jimalalud",
    "La Libertad",
    "Mabinay",
    "Manjuyod",
    "Pamplona",
    "San Jose",
    "Santa Catalina",
    "Siaton",
    "Sibulan",
    "Tanjay",
    "Tayasan",
    "Valencia",
    "Vallehermoso",
    "Zamboanguita"
  ],
  "Siquijor": [
    "Enrique Villanueva",
    "Larena",
    "Lazi",
    "Maria",
    "San Juan",
    "Siquijor"
  ],
  "Biliran": [
    "Almeria",
    "Biliran",
    "Cabucgayan",
    "Caibiran",
    "Culaba",
    "Kawayan",
    "Maripipi",
    "Naval"
  ],
  "Eastern Samar": [
    "Arteche",
    "Balangiga",
    "Balangkayan",
    "Borongan",
    "Can-avid",
    "Dolores",
    "General MacArthur",
    "Giporlos",
    "Guiuan",
    "Hernani",
    "Jipapad",
    "Lawaan",
    "Llorente",
    "Maslog",
    "Maydolong",
    "Mercedes",
    "Oras",
    "Quinapondan",
    "Salcedo",
    "San Julian",
    "San Policarpo",
    "Sulat",
    "Taft"
  ],
  "Leyte": [
    "Abuyog",
    "Alangalang",
    "Albuera",
    "Babatngon",
    "Barugo",
    "Bato",
    "Baybay",
    "Burauen",
    "Calubian",
    "Capoocan",
    "Carigara",
    "Dagami",
    "Dulag",
    "Hilongos",
    "Hindang",
    "Inopacan",
    "Isabel",
    "Jaro",
    "Javier",
    "Julita",
    "Kananga",
    "La Paz",
    "Leyte",
    "MacArthur",
    "Mahaplag",
    "Matag-ob",
    "Matalom",
    "Mayorga",
    "Merida",
    "Ormoc",
    "Palo",
    "Palompon",
    "Pastrana",
    "San Isidro",
    "San Miguel",
    "Santa Fe",
    "Tabango",
    "Tabontabon",
    "Tacloban",
    "Tanauan",
    "Tolosa",
    "Tunga",
    "Villaba"
  ],
  "Northern Samar": [
    "Allen",
    "Biri",
    "Bobon",
    "Capul",
    "Catarman",
    "Catubig",
    "Gamay",
    "Laoang",
    "Lapinig",
    "Las Navas",
    "Lavezares",
    "Lope de Vega",
    "Mapanas",
    "Mondragon",
    "Palapag",
    "Pambujan",
    "Rosario",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Silvino Lobos",
    "Victoria"
  ],
  "Samar": [
    "Almagro",
    "Basey",
    "Calbayog",
    "Calbiga",
    "Catbalogan",
    "Daram",
    "Gandara",
    "Hinabangan",
    "Jiabong",
    "Marabut",
    "Matuguinao",
    "Motiong",
    "Pagsanghan",
    "Paranas",
    "Pinabacdao",
    "San Jorge",
    "San Jose de Buan",
    "San Sebastian",
    "Santa Margarita",
    "Santa Rita",
    "Santo Niño",
    "Tagapul-an",
    "Talalora",
    "Tarangnan",
    "Villareal",
    "Zumarraga"
  ],
  "Southern Leyte": [
    "Anahawan",
    "Bontoc",
    "Hinunangan",
    "Hinundayan",
    "Libagon",
    "Liloan",
    "Limasawa",
    "Maasin",
    "Macrohon",
    "Malitbog",
    "Padre Burgos",
    "Pintuyan",
    "Saint Bernard",
    "San Francisco",
    "San Juan",
    "San Ricardo",
    "Silago",
    "Sogod",
    "Tomas Oppus"
  ],
  "Zamboanga del Norte": [
    "Baliguian",
    "Dapitan",
    "Dipolog",
    "Godod",
    "Gutalac",
    "Jose Dalman",
    "Kalawit",
    "Katipunan",
    "La Libertad",
    "Labason",
    "Leon B. Postigo",
    "Liloy",
    "Manukan",
    "Mutia",
    "Piñan",
    "Polanco",
    "President Manuel A. Roxas",
    "Rizal",
    "Salug",
    "Sergio Osmeña Sr.",
    "Siayan",
    "Sibuco",
    "Sibutad",
    "Sindangan",
    "Siocon",
    "Sirawai",
    "Tampilisan"
  ],
  "Zamboanga del Sur": [
    "Aurora",
    "Bayog",
    "Dimataling",
    "Dinas",
    "Dumalinao",
    "Dumingag",
    "Guipos",
    "Josefina",
    "Kumalarang",
    "Labangan",
    "Lakewood",
    "Lapuyan",
    "Mahayag",
    "Margosatubig",
    "Midsalip",
    "Molave",
    "Pagadian",
    "Pitogo",
    "Ramon Magsaysay",
    "San Miguel",
    "San Pablo",
    "Sominot",
    "Tabina",
    "Tambulig",
    "Tigbao",
    "Tukuran",
    "Vincenzo A. Sagun",
    "Zamboanga City"
  ],
  "Zamboanga Sibugay": [
    "Alicia",
    "Buug",
    "Diplahan",
    "Imelda",
    "Ipil",
    "Kabasalan",
    "Mabuhay",
    "Malangas",
    "Naga",
    "Olutanga",
    "Payao",
    "Roseller T. Lim",
    "Siay",
    "Talusan",
    "Titay",
    "Tungawan"
  ],
  "Bukidnon": [
    "Baungon",
    "Cabanglasan",
    "Damulog",
    "Dangcagan",
    "Don Carlos",
    "Impasug-ong",
    "Kadingilan",
    "Kalilangan",
    "Kibawe",
    "Kitaotao",
    "Lantapan",
    "Libona",
    "Malitbog",
    "Malaybalay",
    "Manolo Fortich",
    "Maramag",
    "Pangantucan",
    "Quezon",
    "San Fernando",
    "Sumilao",
    "Talakag",
    "Valencia"
  ],
  "Camiguin": [
    "Catarman",
    "Guinsiliban",
    "Mahinog",
    "Mambajao",
    "Sagay"
  ],
  "Lanao del Norte": [
    "Bacolod",
    "Baloi",
    "Baroy",
    "Iligan",
    "Kapatagan",
    "Kauswagan",
    "Kolambugan",
    "Lala",
    "Linamon",
    "Magsaysay",
    "Maigo",
    "Matungao",
    "Munai",
    "Nunungan",
    "Pantao Ragat",
    "Pantar",
    "Poona Piagapo",
    "Salvador",
    "Sapad",
    "Sultan Naga Dimaporo",
    "Tagoloan",
    "Tangcal",
    "Tubod"
  ],
  "Misamis Occidental": [
    "Aloran",
    "Baliangao",
    "Bonifacio",
    "Calamba",
    "Clarin",
    "Concepcion",
    "Don Victoriano Chiongbian",
    "Jimenez",
    "Lopez Jaena",
    "Oroquieta",
    "Ozamiz",
    "Panaon",
    "Plaridel",
    "Sapang Dalaga",
    "Sinacaban",
    "Tangub",
    "Tudela"
  ],
  "Misamis Oriental": [
    "Alubijid",
    "Balingasag",
    "Balingoan",
    "Binuangan",
    "Cagayan de Oro",
    "Claveria",
    "El Salvador",
    "Gingoog",
    "Gitagum",
    "Initao",
    "Jasaan",
    "Kinoguitan",
    "Lagonglong",
    "Libertad",
    "Lugait",
    "Magsaysay",
    "Manticao",
    "Medina",
    "Naawan",
    "Opol",
    "Salay",
    "Sugbongcogon",
    "Tagoloan",
    "Talisayan",
    "Villanueva"
  ],
  "Davao de Oro": [
    "Compostela",
    "Laak",
    "Mabini",
    "Maco",
    "Maragusan",
    "Mawab",
    "Monkayo",
    "Montevista",
    "Nabunturan",
    "New Bataan",
    "Pantukan"
  ],
  "Davao del Norte": [
    "Asuncion",
    "Braulio E. Dujali",
    "Carmen",
    "Kapalong",
    "New Corella",
    "Panabo",
    "Samal",
    "San Isidro",
    "Santo Tomas",
    "Tagum",
    "Talaingod"
  ],
  "Davao del Sur": [
    "Bansalan",
    "Davao City",
    "Digos",
    "Hagonoy",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Matanao",
    "Padada",
    "Santa Cruz",
    "Sulop"
  ],
  "Davao Occidental": [
    "Don Marcelino",
    "Jose Abad Santos",
    "Malita",
    "Santa Maria",
    "Sarangani"
  ],
  "Davao Oriental": [
    "Baganga",
    "Banaybanay",
    "Boston",
    "Caraga",
    "Cateel",
    "Governor Generoso",
    "Lupon",
    "Manay",
    "Mati",
    "San Isidro",
    "Tarragona"
  ],
  "Cotabato": [
    "Alamada",
    "Aleosan",
    "Antipas",
    "Arakan",
    "Banisilan",
    "Carmen",
    "Kabacan",
    "Kidapawan",
    "Libungan",
    "Magpet",
    "Makilala",
    "Matalam",
    "Midsayap",
    "M'lang",
    "Pigcawayan",
    "Pikit",
    "President Roxas",
    "Tulunan"
  ],
  "Sarangani": [
    "Alabel",
    "Glan",
    "Kiamba",
    "Maasim",
    "Maitum",
    "Malapatan",
    "Malungon"
  ],
  "South Cotabato": [
    "Banga",
    "General Santos",
    "Koronadal",
    "Lake Sebu",
    "Norala",
    "Polomolok",
    "Santo Niño",
    "Surallah",
    "Tampakan",
    "Tantangan",
    "T'boli",
    "Tupi"
  ],
  "Sultan Kudarat": [
    "Bagumbayan",
    "Columbio",
    "Esperanza",
    "Isulan",
    "Kalamansig",
    "Lambayong",
    "Lebak",
    "Lutayan",
    "Palimbang",
    "President Quirino",
    "Senator Ninoy Aquino",
    "Tacurong"
  ],
  "Agusan del Norte": [
    "Buenavista",
    "Butuan",
    "Cabadbaran",
    "Carmen",
    "Jabonga",
    "Kitcharao",
    "Las Nieves",
    "Magallanes",
    "Nasipit",
    "Remedios T. Romualdez",
    "Santiago",
    "Tubay"
  ],
  "Agusan del Sur": [
    "Bayugan",
    "Bunawan",
    "Esperanza",
    "La Paz",
    "Loreto",
    "Prosperidad",
    "Rosario",
    "San Francisco",
    "San Luis",
    "Santa Josefa",
    "Sibagat",
    "Talacogon",
    "Trento",
    "Veruela"
  ],
  "Dinagat Islands": [
    "Basilisa",
    "Cagdianao",
    "Dinagat",
    "Libjo",
    "Loreto",
    "San Jose",
    "Tubajon"
  ],
  "Surigao del Norte": [
    "Alegria",
    "Bacuag",
    "Burgos",
    "Claver",
    "Dapa",
    "Del Carmen",
    "General Luna",
    "Gigaquit",
    "Mainit",
    "Malimono",
    "Pilar",
    "Placer",
    "San Benito",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "Santa Monica",
    "Sison",
    "Socorro",
    "Surigao City",
    "Tagana-an",
    "Tubod"
  ],
  "Surigao del Sur": [
    "Barobo",
    "Bayabas",
    "Bislig",
    "Cagwait",
    "Cantilan",
    "Carmen",
    "Carrascal",
    "Cortes",
    "Hinatuan",
    "Lanuza",
    "Lianga",
    "Lingig",
    "Madrid",
    "Marihatag",
    "San Agustin",
    "San Miguel",
    "Tagbina",
    "Tago",
    "Tandag"
  ],
  "Basilan": [
    "Akbar",
    "Al-Barka",
    "Hadji Mohammad Ajul",
    "Hadji Muhtamad",
    "Isabela",
    "Lamitan",
    "Lantawan",
    "Maluso",
    "Sumisip",
    "Tipo-Tipo",
    "Tuburan",
    "Ungkaya Pukan"
  ],
  "Lanao del Sur": [
    "Amai Manabilang",
    "Bacolod-Kalawi",
    "Balabagan",
    "Balindong",
    "Bayang",
    "Binidayan",
    "Buadiposo-Buntong",
    "Bubong",
    "Butig",
    "Calanogas",
    "Ditsaan-Ramain",
    "Ganassi",
    "Kapai",
    "Kapatagan",
    "Lumba-Bayabao",
    "Lumbaca-Unayan",
    "Lumbatan",
    "Lumbayanague",
    "Madalum",
    "Madamba",
    "Maguing",
    "Malabang",
    "Marantao",
    "Marawi",
    "Marogong",
    "Masiu",
    "Mulondo",
    "Pagayawan",
    "Piagapo",
    "Picong",
    "Poona Bayabao",
    "Pualas",
    "Saguiaran",
    "Sultan Dumalondong",
    "Tagoloan II",
    "Tamparan",
    "Taraka",
    "Tubaran",
    "Tugaya",
    "Wao"
  ],
  "Maguindanao del Norte": [
    "Barira",
    "Buldon",
    "Cotabato City",
    "Datu Blah T. Sinsuat",
    "Datu Odin Sinsuat",
    "Kabuntalan",
    "Matanog",
    "Northern Kabuntalan",
    "Parang",
    "Sultan Kudarat",
    "Sultan Mastura",
    "Upi"
  ],
  "Maguindanao del Sur": [
    "Ampatuan",
    "Buluan",
    "Datu Abdullah Sangki",
    "Datu Anggal Midtimbang",
    "Datu Hoffer Ampatuan",
    "Datu Montawal",
    "Datu Paglas",
    "Datu Piang",
    "Datu Salibo",
    "Datu Saudi-Ampatuan",
    "Datu Unsay",
    "General Salipada K. Pendatun",
    "Guindulungan",
    "Mamasapano",
    "Mangudadatu",
    "Pagalungan",
    "Paglat",
    "Pandag",
    "Rajah Buayan",
    "Shariff Aguak",
    "Shariff Saydona Mustapha",
    "South Upi",
    "Sultan sa Barongis",
    "Sultan Sumagka",
    "Talayan",
    "Talitay"
  ],
  "Sulu": [
    "Banguingui",
    "Hadji Panglima Tahil",
    "Indanan",
    "Jolo",
    "Kalingalan Caluang",
    "Lugus",
    "Luuk",
    "Maimbung",
    "Old Panamao",
    "Omar",
    "Pandami",
    "Panglima Estino",
    "Pangutaran",
    "Parang",
    "Pata",
    "Patikul",
    "Siasi",
    "Talipao",
    "Tapul",
    "Tongkil"
  ],
  "Tawi-Tawi": [
    "Bongao",
    "Languyan",
    "Mapun",
    "Panglima Sugala",
    "Sapa-Sapa",
    "Sibutu",
    "Simunul",
    "Sitangkai",
    "South Ubian",
    "Tandubas",
    "Turtle Islands"
  ]
};

const CITY_PROVINCE = {
  "Caloocan": "Metro Manila",
  "Las Piñas": "Metro Manila",
  "Makati": "Metro Manila",
  "Malabon": "Metro Manila",
  "Mandaluyong": "Metro Manila",
  "Manila": "Metro Manila",
  "Marikina": "Metro Manila",
  "Muntinlupa": "Metro Manila",
  "Navotas": "Metro Manila",
  "Parañaque": "Metro Manila",
  "Pasay": "Metro Manila",
  "Pasig": "Metro Manila",
  "Pateros": "Metro Manila",
  "Quezon City": "Metro Manila",
  "San Juan": "Metro Manila",
  "Taguig": "Metro Manila",
  "Valenzuela": "Metro Manila",
  "Bangued": "Abra",
  "Boliney": "Abra",
  "Bucay": "Abra",
  "Bucloc": "Abra",
  "Daguioman": "Abra",
  "Danglas": "Abra",
  "Dolores": "Abra",
  "La Paz": "Abra",
  "Lacub": "Abra",
  "Lagangilang": "Abra",
  "Lagayan": "Abra",
  "Langiden": "Abra",
  "Licuan-Baay": "Abra",
  "Luba": "Abra",
  "Malibcong": "Abra",
  "Manabo": "Abra",
  "Peñarrubia": "Abra",
  "Pidigan": "Abra",
  "Pilar": "Abra",
  "Sallapadan": "Abra",
  "San Isidro": "Abra",
  "San Quintin": "Abra",
  "Tayum": "Abra",
  "Tineg": "Abra",
  "Tubo": "Abra",
  "Villaviciosa": "Abra",
  "Calanasan": "Apayao",
  "Conner": "Apayao",
  "Flora": "Apayao",
  "Kabugao": "Apayao",
  "Luna": "Apayao",
  "Pudtol": "Apayao",
  "Santa Marcela": "Apayao",
  "Atok": "Benguet",
  "Baguio": "Benguet",
  "Bakun": "Benguet",
  "Bokod": "Benguet",
  "Buguias": "Benguet",
  "Itogon": "Benguet",
  "Kabayan": "Benguet",
  "Kapangan": "Benguet",
  "Kibungan": "Benguet",
  "La Trinidad": "Benguet",
  "Mankayan": "Benguet",
  "Sablan": "Benguet",
  "Tuba": "Benguet",
  "Tublay": "Benguet",
  "Aguinaldo": "Ifugao",
  "Alfonso Lista": "Ifugao",
  "Asipulo": "Ifugao",
  "Banaue": "Ifugao",
  "Hingyon": "Ifugao",
  "Hungduan": "Ifugao",
  "Kiangan": "Ifugao",
  "Lagawe": "Ifugao",
  "Lamut": "Ifugao",
  "Mayoyao": "Ifugao",
  "Tinoc": "Ifugao",
  "Balbalan": "Kalinga",
  "Lubuagan": "Kalinga",
  "Pasil": "Kalinga",
  "Pinukpuk": "Kalinga",
  "Rizal": "Kalinga",
  "Tabuk": "Kalinga",
  "Tanudan": "Kalinga",
  "Tinglayan": "Kalinga",
  "Barlig": "Mountain Province",
  "Bauko": "Mountain Province",
  "Besao": "Mountain Province",
  "Bontoc": "Mountain Province",
  "Natonin": "Mountain Province",
  "Paracelis": "Mountain Province",
  "Sabangan": "Mountain Province",
  "Sadanga": "Mountain Province",
  "Sagada": "Mountain Province",
  "Tadian": "Mountain Province",
  "Adams": "Ilocos Norte",
  "Bacarra": "Ilocos Norte",
  "Badoc": "Ilocos Norte",
  "Bangui": "Ilocos Norte",
  "Banna": "Ilocos Norte",
  "Batac": "Ilocos Norte",
  "Burgos": "Ilocos Norte",
  "Carasi": "Ilocos Norte",
  "Currimao": "Ilocos Norte",
  "Dingras": "Ilocos Norte",
  "Dumalneg": "Ilocos Norte",
  "Laoag": "Ilocos Norte",
  "Marcos": "Ilocos Norte",
  "Nueva Era": "Ilocos Norte",
  "Pagudpud": "Ilocos Norte",
  "Paoay": "Ilocos Norte",
  "Pasuquin": "Ilocos Norte",
  "Piddig": "Ilocos Norte",
  "Pinili": "Ilocos Norte",
  "San Nicolas": "Ilocos Norte",
  "Sarrat": "Ilocos Norte",
  "Solsona": "Ilocos Norte",
  "Vintar": "Ilocos Norte",
  "Alilem": "Ilocos Sur",
  "Banayoyo": "Ilocos Sur",
  "Bantay": "Ilocos Sur",
  "Cabugao": "Ilocos Sur",
  "Candon": "Ilocos Sur",
  "Caoayan": "Ilocos Sur",
  "Cervantes": "Ilocos Sur",
  "Galimuyod": "Ilocos Sur",
  "Gregorio del Pilar": "Ilocos Sur",
  "Lidlidda": "Ilocos Sur",
  "Magsingal": "Ilocos Sur",
  "Nagbukel": "Ilocos Sur",
  "Narvacan": "Ilocos Sur",
  "Quirino": "Ilocos Sur",
  "Salcedo": "Ilocos Sur",
  "San Emilio": "Ilocos Sur",
  "San Esteban": "Ilocos Sur",
  "San Ildefonso": "Ilocos Sur",
  "San Vicente": "Ilocos Sur",
  "Santa": "Ilocos Sur",
  "Santa Catalina": "Ilocos Sur",
  "Santa Cruz": "Ilocos Sur",
  "Santa Lucia": "Ilocos Sur",
  "Santa Maria": "Ilocos Sur",
  "Santiago": "Ilocos Sur",
  "Santo Domingo": "Ilocos Sur",
  "Sigay": "Ilocos Sur",
  "Sinait": "Ilocos Sur",
  "Sugpon": "Ilocos Sur",
  "Suyo": "Ilocos Sur",
  "Tagudin": "Ilocos Sur",
  "Vigan": "Ilocos Sur",
  "Agoo": "La Union",
  "Aringay": "La Union",
  "Bacnotan": "La Union",
  "Bagulin": "La Union",
  "Balaoan": "La Union",
  "Bangar": "La Union",
  "Bauang": "La Union",
  "Caba": "La Union",
  "Naguilian": "La Union",
  "Pugo": "La Union",
  "Rosario": "La Union",
  "San Fernando": "La Union",
  "San Gabriel": "La Union",
  "Santol": "La Union",
  "Santo Tomas": "La Union",
  "Sudipen": "La Union",
  "Tubao": "La Union",
  "Agno": "Pangasinan",
  "Aguilar": "Pangasinan",
  "Alaminos": "Pangasinan",
  "Alcala": "Pangasinan",
  "Anda": "Pangasinan",
  "Asingan": "Pangasinan",
  "Balungao": "Pangasinan",
  "Bani": "Pangasinan",
  "Basista": "Pangasinan",
  "Bautista": "Pangasinan",
  "Bayambang": "Pangasinan",
  "Binalonan": "Pangasinan",
  "Binmaley": "Pangasinan",
  "Bolinao": "Pangasinan",
  "Bugallon": "Pangasinan",
  "Calasiao": "Pangasinan",
  "Dagupan": "Pangasinan",
  "Dasol": "Pangasinan",
  "Infanta": "Pangasinan",
  "Labrador": "Pangasinan",
  "Laoac": "Pangasinan",
  "Lingayen": "Pangasinan",
  "Mabini": "Pangasinan",
  "Malasiqui": "Pangasinan",
  "Manaoag": "Pangasinan",
  "Mangaldan": "Pangasinan",
  "Mangatarem": "Pangasinan",
  "Mapandan": "Pangasinan",
  "Natividad": "Pangasinan",
  "Pozorrubio": "Pangasinan",
  "Rosales": "Pangasinan",
  "San Carlos": "Pangasinan",
  "San Fabian": "Pangasinan",
  "San Jacinto": "Pangasinan",
  "San Manuel": "Pangasinan",
  "Santa Barbara": "Pangasinan",
  "Sison": "Pangasinan",
  "Sual": "Pangasinan",
  "Tayug": "Pangasinan",
  "Umingan": "Pangasinan",
  "Urbiztondo": "Pangasinan",
  "Urdaneta": "Pangasinan",
  "Villasis": "Pangasinan",
  "Basco": "Batanes",
  "Itbayat": "Batanes",
  "Ivana": "Batanes",
  "Mahatao": "Batanes",
  "Sabtang": "Batanes",
  "Uyugan": "Batanes",
  "Abulug": "Cagayan",
  "Allacapan": "Cagayan",
  "Amulung": "Cagayan",
  "Aparri": "Cagayan",
  "Baggao": "Cagayan",
  "Ballesteros": "Cagayan",
  "Buguey": "Cagayan",
  "Calayan": "Cagayan",
  "Camalaniugan": "Cagayan",
  "Claveria": "Cagayan",
  "Enrile": "Cagayan",
  "Gattaran": "Cagayan",
  "Gonzaga": "Cagayan",
  "Iguig": "Cagayan",
  "Lal-lo": "Cagayan",
  "Lasam": "Cagayan",
  "Pamplona": "Cagayan",
  "Peñablanca": "Cagayan",
  "Piat": "Cagayan",
  "Sanchez-Mira": "Cagayan",
  "Santa Ana": "Cagayan",
  "Santa Praxedes": "Cagayan",
  "Santa Teresita": "Cagayan",
  "Santo Niño": "Cagayan",
  "Solana": "Cagayan",
  "Tuao": "Cagayan",
  "Tuguegarao": "Cagayan",
  "Alicia": "Isabela",
  "Angadanan": "Isabela",
  "Aurora": "Isabela",
  "Benito Soliven": "Isabela",
  "Cabagan": "Isabela",
  "Cabatuan": "Isabela",
  "Cauayan": "Isabela",
  "Cordon": "Isabela",
  "Delfin Albano": "Isabela",
  "Dinapigue": "Isabela",
  "Divilacan": "Isabela",
  "Echague": "Isabela",
  "Gamu": "Isabela",
  "Ilagan": "Isabela",
  "Jones": "Isabela",
  "Maconacon": "Isabela",
  "Mallig": "Isabela",
  "Palanan": "Isabela",
  "Quezon": "Isabela",
  "Ramon": "Isabela",
  "Reina Mercedes": "Isabela",
  "Roxas": "Isabela",
  "San Agustin": "Isabela",
  "San Guillermo": "Isabela",
  "San Mariano": "Isabela",
  "San Mateo": "Isabela",
  "San Pablo": "Isabela",
  "Tumauini": "Isabela",
  "Alfonso Castañeda": "Nueva Vizcaya",
  "Ambaguio": "Nueva Vizcaya",
  "Aritao": "Nueva Vizcaya",
  "Bagabag": "Nueva Vizcaya",
  "Bambang": "Nueva Vizcaya",
  "Bayombong": "Nueva Vizcaya",
  "Diadi": "Nueva Vizcaya",
  "Dupax del Norte": "Nueva Vizcaya",
  "Dupax del Sur": "Nueva Vizcaya",
  "Kasibu": "Nueva Vizcaya",
  "Kayapa": "Nueva Vizcaya",
  "Santa Fe": "Nueva Vizcaya",
  "Solano": "Nueva Vizcaya",
  "Villaverde": "Nueva Vizcaya",
  "Aglipay": "Quirino",
  "Cabarroguis": "Quirino",
  "Diffun": "Quirino",
  "Maddela": "Quirino",
  "Nagtipunan": "Quirino",
  "Saguday": "Quirino",
  "Baler": "Aurora",
  "Casiguran": "Aurora",
  "Dilasag": "Aurora",
  "Dinalungan": "Aurora",
  "Dingalan": "Aurora",
  "Dipaculao": "Aurora",
  "Maria Aurora": "Aurora",
  "San Luis": "Aurora",
  "Abucay": "Bataan",
  "Bagac": "Bataan",
  "Balanga": "Bataan",
  "Dinalupihan": "Bataan",
  "Hermosa": "Bataan",
  "Limay": "Bataan",
  "Mariveles": "Bataan",
  "Morong": "Bataan",
  "Orani": "Bataan",
  "Orion": "Bataan",
  "Samal": "Bataan",
  "Angat": "Bulacan",
  "Balagtas": "Bulacan",
  "Baliuag": "Bulacan",
  "Bocaue": "Bulacan",
  "Bulakan": "Bulacan",
  "Bustos": "Bulacan",
  "Calumpit": "Bulacan",
  "Doña Remedios Trinidad": "Bulacan",
  "Guiguinto": "Bulacan",
  "Hagonoy": "Bulacan",
  "Malolos": "Bulacan",
  "Marilao": "Bulacan",
  "Meycauayan": "Bulacan",
  "Norzagaray": "Bulacan",
  "Obando": "Bulacan",
  "Pandi": "Bulacan",
  "Paombong": "Bulacan",
  "Plaridel": "Bulacan",
  "Pulilan": "Bulacan",
  "San Jose del Monte": "Bulacan",
  "San Miguel": "Bulacan",
  "San Rafael": "Bulacan",
  "Aliaga": "Nueva Ecija",
  "Bongabon": "Nueva Ecija",
  "Cabiao": "Nueva Ecija",
  "Cabanatuan": "Nueva Ecija",
  "Carranglan": "Nueva Ecija",
  "Cuyapo": "Nueva Ecija",
  "Gabaldon": "Nueva Ecija",
  "Gapan": "Nueva Ecija",
  "General Mamerto Natividad": "Nueva Ecija",
  "General Tinio": "Nueva Ecija",
  "Guimba": "Nueva Ecija",
  "Jaen": "Nueva Ecija",
  "Laur": "Nueva Ecija",
  "Licab": "Nueva Ecija",
  "Llanera": "Nueva Ecija",
  "Lupao": "Nueva Ecija",
  "Muñoz": "Nueva Ecija",
  "Nampicuan": "Nueva Ecija",
  "Palayan": "Nueva Ecija",
  "Pantabangan": "Nueva Ecija",
  "Peñaranda": "Nueva Ecija",
  "San Antonio": "Nueva Ecija",
  "San Jose": "Nueva Ecija",
  "San Leonardo": "Nueva Ecija",
  "Santa Rosa": "Nueva Ecija",
  "Talavera": "Nueva Ecija",
  "Talugtug": "Nueva Ecija",
  "Zaragoza": "Nueva Ecija",
  "Angeles": "Pampanga",
  "Apalit": "Pampanga",
  "Arayat": "Pampanga",
  "Bacolor": "Pampanga",
  "Candaba": "Pampanga",
  "Floridablanca": "Pampanga",
  "Guagua": "Pampanga",
  "Lubao": "Pampanga",
  "Mabalacat": "Pampanga",
  "Macabebe": "Pampanga",
  "Magalang": "Pampanga",
  "Masantol": "Pampanga",
  "Mexico": "Pampanga",
  "Minalin": "Pampanga",
  "Porac": "Pampanga",
  "San Simon": "Pampanga",
  "Santa Rita": "Pampanga",
  "Sasmuan": "Pampanga",
  "Anao": "Tarlac",
  "Bamban": "Tarlac",
  "Camiling": "Tarlac",
  "Capas": "Tarlac",
  "Concepcion": "Tarlac",
  "Gerona": "Tarlac",
  "Mayantoc": "Tarlac",
  "Moncada": "Tarlac",
  "Paniqui": "Tarlac",
  "Pura": "Tarlac",
  "Ramos": "Tarlac",
  "San Clemente": "Tarlac",
  "Santa Ignacia": "Tarlac",
  "Tarlac City": "Tarlac",
  "Victoria": "Tarlac",
  "Botolan": "Zambales",
  "Cabangan": "Zambales",
  "Candelaria": "Zambales",
  "Castillejos": "Zambales",
  "Iba": "Zambales",
  "Masinloc": "Zambales",
  "Olongapo": "Zambales",
  "Palauig": "Zambales",
  "San Felipe": "Zambales",
  "San Marcelino": "Zambales",
  "San Narciso": "Zambales",
  "San Salvador": "Zambales",
  "Subic": "Zambales",
  "Agoncillo": "Batangas",
  "Alitagtag": "Batangas",
  "Balayan": "Batangas",
  "Balete": "Batangas",
  "Batangas City": "Batangas",
  "Bauan": "Batangas",
  "Calaca": "Batangas",
  "Calatagan": "Batangas",
  "Cuenca": "Batangas",
  "Ibaan": "Batangas",
  "Laurel": "Batangas",
  "Lemery": "Batangas",
  "Lian": "Batangas",
  "Lipa": "Batangas",
  "Lobo": "Batangas",
  "Malvar": "Batangas",
  "Mataasnakahoy": "Batangas",
  "Nasugbu": "Batangas",
  "Padre Garcia": "Batangas",
  "San Pascual": "Batangas",
  "Taal": "Batangas",
  "Talisay": "Batangas",
  "Tanauan": "Batangas",
  "Taysan": "Batangas",
  "Tingloy": "Batangas",
  "Tuy": "Batangas",
  "Alfonso": "Cavite",
  "Amadeo": "Cavite",
  "Bacoor": "Cavite",
  "Carmona": "Cavite",
  "Cavite City": "Cavite",
  "Dasmariñas": "Cavite",
  "General Emilio Aguinaldo": "Cavite",
  "General Mariano Alvarez": "Cavite",
  "General Trias": "Cavite",
  "Imus": "Cavite",
  "Indang": "Cavite",
  "Kawit": "Cavite",
  "Magallanes": "Cavite",
  "Maragondon": "Cavite",
  "Mendez": "Cavite",
  "Naic": "Cavite",
  "Noveleta": "Cavite",
  "Silang": "Cavite",
  "Tagaytay": "Cavite",
  "Tanza": "Cavite",
  "Ternate": "Cavite",
  "Trece Martires": "Cavite",
  "Bay": "Laguna",
  "Biñan": "Laguna",
  "Cabuyao": "Laguna",
  "Calamba": "Laguna",
  "Calauan": "Laguna",
  "Cavinti": "Laguna",
  "Famy": "Laguna",
  "Kalayaan": "Laguna",
  "Liliw": "Laguna",
  "Los Baños": "Laguna",
  "Luisiana": "Laguna",
  "Lumban": "Laguna",
  "Mabitac": "Laguna",
  "Magdalena": "Laguna",
  "Majayjay": "Laguna",
  "Nagcarlan": "Laguna",
  "Paete": "Laguna",
  "Pagsanjan": "Laguna",
  "Pakil": "Laguna",
  "Pangil": "Laguna",
  "Pila": "Laguna",
  "San Pedro": "Laguna",
  "Siniloan": "Laguna",
  "Agdangan": "Quezon",
  "Alabat": "Quezon",
  "Atimonan": "Quezon",
  "Buenavista": "Quezon",
  "Burdeos": "Quezon",
  "Calauag": "Quezon",
  "Catanauan": "Quezon",
  "General Luna": "Quezon",
  "General Nakar": "Quezon",
  "Guinayangan": "Quezon",
  "Gumaca": "Quezon",
  "Jomalig": "Quezon",
  "Lopez": "Quezon",
  "Lucban": "Quezon",
  "Lucena": "Quezon",
  "Macalelon": "Quezon",
  "Mauban": "Quezon",
  "Mulanay": "Quezon",
  "Padre Burgos": "Quezon",
  "Pagbilao": "Quezon",
  "Panukulan": "Quezon",
  "Patnanungan": "Quezon",
  "Perez": "Quezon",
  "Pitogo": "Quezon",
  "Polillo": "Quezon",
  "Real": "Quezon",
  "Sampaloc": "Quezon",
  "San Andres": "Quezon",
  "San Francisco": "Quezon",
  "Sariaya": "Quezon",
  "Tagkawayan": "Quezon",
  "Tayabas": "Quezon",
  "Tiaong": "Quezon",
  "Unisan": "Quezon",
  "Angono": "Rizal",
  "Antipolo": "Rizal",
  "Baras": "Rizal",
  "Binangonan": "Rizal",
  "Cainta": "Rizal",
  "Cardona": "Rizal",
  "Jalajala": "Rizal",
  "Pililla": "Rizal",
  "Rodriguez": "Rizal",
  "Tanay": "Rizal",
  "Taytay": "Rizal",
  "Teresa": "Rizal",
  "Boac": "Marinduque",
  "Gasan": "Marinduque",
  "Mogpog": "Marinduque",
  "Torrijos": "Marinduque",
  "Abra de Ilog": "Occidental Mindoro",
  "Calintaan": "Occidental Mindoro",
  "Looc": "Occidental Mindoro",
  "Lubang": "Occidental Mindoro",
  "Magsaysay": "Occidental Mindoro",
  "Mamburao": "Occidental Mindoro",
  "Paluan": "Occidental Mindoro",
  "Sablayan": "Occidental Mindoro",
  "Baco": "Oriental Mindoro",
  "Bansud": "Oriental Mindoro",
  "Bongabong": "Oriental Mindoro",
  "Bulalacao": "Oriental Mindoro",
  "Calapan": "Oriental Mindoro",
  "Gloria": "Oriental Mindoro",
  "Mansalay": "Oriental Mindoro",
  "Naujan": "Oriental Mindoro",
  "Pinamalayan": "Oriental Mindoro",
  "Pola": "Oriental Mindoro",
  "Puerto Galera": "Oriental Mindoro",
  "San Teodoro": "Oriental Mindoro",
  "Socorro": "Oriental Mindoro",
  "Aborlan": "Palawan",
  "Agutaya": "Palawan",
  "Araceli": "Palawan",
  "Balabac": "Palawan",
  "Bataraza": "Palawan",
  "Brooke's Point": "Palawan",
  "Busuanga": "Palawan",
  "Cagayancillo": "Palawan",
  "Coron": "Palawan",
  "Culion": "Palawan",
  "Cuyo": "Palawan",
  "Dumaran": "Palawan",
  "El Nido": "Palawan",
  "Linapacan": "Palawan",
  "Narra": "Palawan",
  "Puerto Princesa": "Palawan",
  "Sofronio Española": "Palawan",
  "Alcantara": "Romblon",
  "Banton": "Romblon",
  "Cajidiocan": "Romblon",
  "Calatrava": "Romblon",
  "Corcuera": "Romblon",
  "Ferrol": "Romblon",
  "Magdiwang": "Romblon",
  "Odiongan": "Romblon",
  "Romblon": "Romblon",
  "Sibuyan": "Romblon",
  "Bacacay": "Albay",
  "Camalig": "Albay",
  "Daraga": "Albay",
  "Guinobatan": "Albay",
  "Jovellar": "Albay",
  "Legazpi": "Albay",
  "Libon": "Albay",
  "Ligao": "Albay",
  "Malilipot": "Albay",
  "Malinao": "Albay",
  "Manito": "Albay",
  "Oas": "Albay",
  "Pio Duran": "Albay",
  "Polangui": "Albay",
  "Rapu-Rapu": "Albay",
  "Tabaco": "Albay",
  "Tiwi": "Albay",
  "Basud": "Camarines Norte",
  "Capalonga": "Camarines Norte",
  "Daet": "Camarines Norte",
  "Jose Panganiban": "Camarines Norte",
  "Labo": "Camarines Norte",
  "Mercedes": "Camarines Norte",
  "Paracale": "Camarines Norte",
  "San Lorenzo Ruiz": "Camarines Norte",
  "Santa Elena": "Camarines Norte",
  "Vinzons": "Camarines Norte",
  "Baao": "Camarines Sur",
  "Balatan": "Camarines Sur",
  "Bato": "Camarines Sur",
  "Bombon": "Camarines Sur",
  "Buhi": "Camarines Sur",
  "Bula": "Camarines Sur",
  "Cabusao": "Camarines Sur",
  "Calabanga": "Camarines Sur",
  "Camaligan": "Camarines Sur",
  "Canaman": "Camarines Sur",
  "Caramoan": "Camarines Sur",
  "Del Gallego": "Camarines Sur",
  "Gainza": "Camarines Sur",
  "Garchitorena": "Camarines Sur",
  "Goa": "Camarines Sur",
  "Iriga": "Camarines Sur",
  "Lagonoy": "Camarines Sur",
  "Libmanan": "Camarines Sur",
  "Lupi": "Camarines Sur",
  "Magarao": "Camarines Sur",
  "Milaor": "Camarines Sur",
  "Minalabac": "Camarines Sur",
  "Nabua": "Camarines Sur",
  "Naga": "Camarines Sur",
  "Ocampo": "Camarines Sur",
  "Pasacao": "Camarines Sur",
  "Pili": "Camarines Sur",
  "Presentacion": "Camarines Sur",
  "Ragay": "Camarines Sur",
  "Sagñay": "Camarines Sur",
  "Sipocot": "Camarines Sur",
  "Siruma": "Camarines Sur",
  "Tigaon": "Camarines Sur",
  "Tinambac": "Camarines Sur",
  "Bagamanoc": "Catanduanes",
  "Caramoran": "Catanduanes",
  "Gigmoto": "Catanduanes",
  "Pandan": "Catanduanes",
  "Panganiban": "Catanduanes",
  "Viga": "Catanduanes",
  "Virac": "Catanduanes",
  "Aroroy": "Masbate",
  "Baleno": "Masbate",
  "Balud": "Masbate",
  "Batuan": "Masbate",
  "Cataingan": "Masbate",
  "Cawayan": "Masbate",
  "Dimasalang": "Masbate",
  "Esperanza": "Masbate",
  "Mandaon": "Masbate",
  "Masbate City": "Masbate",
  "Mobo": "Masbate",
  "Monreal": "Masbate",
  "Palanas": "Masbate",
  "Pio V. Corpuz": "Masbate",
  "Placer": "Masbate",
  "Uson": "Masbate",
  "Barcelona": "Sorsogon",
  "Bulan": "Sorsogon",
  "Bulusan": "Sorsogon",
  "Castilla": "Sorsogon",
  "Donsol": "Sorsogon",
  "Gubat": "Sorsogon",
  "Irosin": "Sorsogon",
  "Juban": "Sorsogon",
  "Matnog": "Sorsogon",
  "Prieto Diaz": "Sorsogon",
  "Santa Magdalena": "Sorsogon",
  "Sorsogon City": "Sorsogon",
  "Altavas": "Aklan",
  "Banga": "Aklan",
  "Batan": "Aklan",
  "Buruanga": "Aklan",
  "Ibajay": "Aklan",
  "Kalibo": "Aklan",
  "Lezo": "Aklan",
  "Libacao": "Aklan",
  "Madalag": "Aklan",
  "Makato": "Aklan",
  "Malay": "Aklan",
  "Nabas": "Aklan",
  "New Washington": "Aklan",
  "Numancia": "Aklan",
  "Tangalan": "Aklan",
  "Anini-y": "Antique",
  "Barbaza": "Antique",
  "Belison": "Antique",
  "Bugasong": "Antique",
  "Caluya": "Antique",
  "Culasi": "Antique",
  "Hamtic": "Antique",
  "Laua-an": "Antique",
  "Libertad": "Antique",
  "Patnongon": "Antique",
  "San Jose de Buenavista": "Antique",
  "San Remigio": "Antique",
  "Sebaste": "Antique",
  "Sibalom": "Antique",
  "Tibiao": "Antique",
  "Tobias Fornier": "Antique",
  "Valderrama": "Antique",
  "Cuartero": "Capiz",
  "Dao": "Capiz",
  "Dumalag": "Capiz",
  "Dumarao": "Capiz",
  "Ivisan": "Capiz",
  "Jamindan": "Capiz",
  "Ma-ayon": "Capiz",
  "Mambusao": "Capiz",
  "Panay": "Capiz",
  "Panitan": "Capiz",
  "Pontevedra": "Capiz",
  "President Roxas": "Capiz",
  "Sapian": "Capiz",
  "Sigma": "Capiz",
  "Tapaz": "Capiz",
  "Jordan": "Guimaras",
  "Nueva Valencia": "Guimaras",
  "San Lorenzo": "Guimaras",
  "Sibunag": "Guimaras",
  "Ajuy": "Iloilo",
  "Alimodian": "Iloilo",
  "Anilao": "Iloilo",
  "Badiangan": "Iloilo",
  "Balasan": "Iloilo",
  "Banate": "Iloilo",
  "Barotac Nuevo": "Iloilo",
  "Barotac Viejo": "Iloilo",
  "Batad": "Iloilo",
  "Bingawan": "Iloilo",
  "Calinog": "Iloilo",
  "Carles": "Iloilo",
  "Dingle": "Iloilo",
  "Dueñas": "Iloilo",
  "Dumangas": "Iloilo",
  "Estancia": "Iloilo",
  "Guimbal": "Iloilo",
  "Igbaras": "Iloilo",
  "Iloilo City": "Iloilo",
  "Janiuay": "Iloilo",
  "Lambunao": "Iloilo",
  "Leganes": "Iloilo",
  "Leon": "Iloilo",
  "Maasin": "Iloilo",
  "Miagao": "Iloilo",
  "Mina": "Iloilo",
  "New Lucena": "Iloilo",
  "Oton": "Iloilo",
  "Passi": "Iloilo",
  "Pavia": "Iloilo",
  "Pototan": "Iloilo",
  "San Dionisio": "Iloilo",
  "San Enrique": "Iloilo",
  "San Joaquin": "Iloilo",
  "Sara": "Iloilo",
  "Tigbauan": "Iloilo",
  "Tubungan": "Iloilo",
  "Zarraga": "Iloilo",
  "Bago": "Negros Occidental",
  "Binalbagan": "Negros Occidental",
  "Cadiz": "Negros Occidental",
  "Candoni": "Negros Occidental",
  "Enrique B. Magalona": "Negros Occidental",
  "Escalante": "Negros Occidental",
  "Himamaylan": "Negros Occidental",
  "Hinigaran": "Negros Occidental",
  "Hinoba-an": "Negros Occidental",
  "Ilog": "Negros Occidental",
  "Isabela": "Negros Occidental",
  "Kabankalan": "Negros Occidental",
  "La Carlota": "Negros Occidental",
  "La Castellana": "Negros Occidental",
  "Manapla": "Negros Occidental",
  "Moises Padilla": "Negros Occidental",
  "Murcia": "Negros Occidental",
  "Pulupandan": "Negros Occidental",
  "Sagay": "Negros Occidental",
  "Salvador Benedicto": "Negros Occidental",
  "Silay": "Negros Occidental",
  "Sipalay": "Negros Occidental",
  "Toboso": "Negros Occidental",
  "Valladolid": "Negros Occidental",
  "Victorias": "Negros Occidental",
  "Alburquerque": "Bohol",
  "Antequera": "Bohol",
  "Baclayon": "Bohol",
  "Balilihan": "Bohol",
  "Bien Unido": "Bohol",
  "Bilar": "Bohol",
  "Calape": "Bohol",
  "Candijay": "Bohol",
  "Carmen": "Bohol",
  "Catigbian": "Bohol",
  "Clarin": "Bohol",
  "Corella": "Bohol",
  "Cortes": "Bohol",
  "Dagohoy": "Bohol",
  "Danao": "Bohol",
  "Dauis": "Bohol",
  "Dimiao": "Bohol",
  "Duero": "Bohol",
  "Garcia Hernandez": "Bohol",
  "Getafe": "Bohol",
  "Guindulman": "Bohol",
  "Inabanga": "Bohol",
  "Jagna": "Bohol",
  "Lila": "Bohol",
  "Loay": "Bohol",
  "Loboc": "Bohol",
  "Loon": "Bohol",
  "Maribojoc": "Bohol",
  "Panglao": "Bohol",
  "President Carlos P. Garcia": "Bohol",
  "Sagbayan": "Bohol",
  "Sevilla": "Bohol",
  "Sierra Bullones": "Bohol",
  "Sikatuna": "Bohol",
  "Tagbilaran": "Bohol",
  "Talibon": "Bohol",
  "Trinidad": "Bohol",
  "Tubigon": "Bohol",
  "Ubay": "Bohol",
  "Valencia": "Bohol",
  "Alcoy": "Cebu",
  "Alegria": "Cebu",
  "Aloguinsan": "Cebu",
  "Argao": "Cebu",
  "Asturias": "Cebu",
  "Badian": "Cebu",
  "Balamban": "Cebu",
  "Bantayan": "Cebu",
  "Barili": "Cebu",
  "Bogo": "Cebu",
  "Boljoon": "Cebu",
  "Borbon": "Cebu",
  "Carcar": "Cebu",
  "Catmon": "Cebu",
  "Cebu City": "Cebu",
  "Compostela": "Cebu",
  "Consolacion": "Cebu",
  "Cordova": "Cebu",
  "Daanbantayan": "Cebu",
  "Dalaguete": "Cebu",
  "Dumanjug": "Cebu",
  "Ginatilan": "Cebu",
  "Liloan": "Cebu",
  "Madridejos": "Cebu",
  "Malabuyoc": "Cebu",
  "Mandaue": "Cebu",
  "Medellin": "Cebu",
  "Minglanilla": "Cebu",
  "Moalboal": "Cebu",
  "Oslob": "Cebu",
  "Pinamungajan": "Cebu",
  "Poro": "Cebu",
  "Ronda": "Cebu",
  "Samboan": "Cebu",
  "Santander": "Cebu",
  "Sibonga": "Cebu",
  "Sogod": "Cebu",
  "Tabogon": "Cebu",
  "Tabuelan": "Cebu",
  "Toledo": "Cebu",
  "Tuburan": "Cebu",
  "Tudela": "Cebu",
  "Amlan": "Negros Oriental",
  "Ayungon": "Negros Oriental",
  "Bacong": "Negros Oriental",
  "Bais": "Negros Oriental",
  "Basay": "Negros Oriental",
  "Bayawan": "Negros Oriental",
  "Bindoy": "Negros Oriental",
  "Dauin": "Negros Oriental",
  "Dumaguete": "Negros Oriental",
  "Guihulngan": "Negros Oriental",
  "Jimalalud": "Negros Oriental",
  "La Libertad": "Negros Oriental",
  "Mabinay": "Negros Oriental",
  "Manjuyod": "Negros Oriental",
  "Siaton": "Negros Oriental",
  "Sibulan": "Negros Oriental",
  "Tanjay": "Negros Oriental",
  "Tayasan": "Negros Oriental",
  "Vallehermoso": "Negros Oriental",
  "Zamboanguita": "Negros Oriental",
  "Enrique Villanueva": "Siquijor",
  "Larena": "Siquijor",
  "Lazi": "Siquijor",
  "Maria": "Siquijor",
  "Siquijor": "Siquijor",
  "Almeria": "Biliran",
  "Biliran": "Biliran",
  "Cabucgayan": "Biliran",
  "Caibiran": "Biliran",
  "Culaba": "Biliran",
  "Kawayan": "Biliran",
  "Maripipi": "Biliran",
  "Naval": "Biliran",
  "Arteche": "Eastern Samar",
  "Balangiga": "Eastern Samar",
  "Balangkayan": "Eastern Samar",
  "Borongan": "Eastern Samar",
  "Can-avid": "Eastern Samar",
  "General MacArthur": "Eastern Samar",
  "Giporlos": "Eastern Samar",
  "Guiuan": "Eastern Samar",
  "Hernani": "Eastern Samar",
  "Jipapad": "Eastern Samar",
  "Lawaan": "Eastern Samar",
  "Llorente": "Eastern Samar",
  "Maslog": "Eastern Samar",
  "Maydolong": "Eastern Samar",
  "Oras": "Eastern Samar",
  "Quinapondan": "Eastern Samar",
  "San Julian": "Eastern Samar",
  "San Policarpo": "Eastern Samar",
  "Sulat": "Eastern Samar",
  "Taft": "Eastern Samar",
  "Abuyog": "Leyte",
  "Alangalang": "Leyte",
  "Albuera": "Leyte",
  "Babatngon": "Leyte",
  "Barugo": "Leyte",
  "Baybay": "Leyte",
  "Burauen": "Leyte",
  "Calubian": "Leyte",
  "Capoocan": "Leyte",
  "Carigara": "Leyte",
  "Dagami": "Leyte",
  "Dulag": "Leyte",
  "Hilongos": "Leyte",
  "Hindang": "Leyte",
  "Inopacan": "Leyte",
  "Isabel": "Leyte",
  "Jaro": "Leyte",
  "Javier": "Leyte",
  "Julita": "Leyte",
  "Kananga": "Leyte",
  "Leyte": "Leyte",
  "MacArthur": "Leyte",
  "Mahaplag": "Leyte",
  "Matag-ob": "Leyte",
  "Matalom": "Leyte",
  "Mayorga": "Leyte",
  "Merida": "Leyte",
  "Ormoc": "Leyte",
  "Palo": "Leyte",
  "Palompon": "Leyte",
  "Pastrana": "Leyte",
  "Tabango": "Leyte",
  "Tabontabon": "Leyte",
  "Tacloban": "Leyte",
  "Tolosa": "Leyte",
  "Tunga": "Leyte",
  "Villaba": "Leyte",
  "Allen": "Northern Samar",
  "Biri": "Northern Samar",
  "Bobon": "Northern Samar",
  "Capul": "Northern Samar",
  "Catarman": "Northern Samar",
  "Catubig": "Northern Samar",
  "Gamay": "Northern Samar",
  "Laoang": "Northern Samar",
  "Lapinig": "Northern Samar",
  "Las Navas": "Northern Samar",
  "Lavezares": "Northern Samar",
  "Lope de Vega": "Northern Samar",
  "Mapanas": "Northern Samar",
  "Mondragon": "Northern Samar",
  "Palapag": "Northern Samar",
  "Pambujan": "Northern Samar",
  "San Roque": "Northern Samar",
  "Silvino Lobos": "Northern Samar",
  "Almagro": "Samar",
  "Basey": "Samar",
  "Calbayog": "Samar",
  "Calbiga": "Samar",
  "Catbalogan": "Samar",
  "Daram": "Samar",
  "Gandara": "Samar",
  "Hinabangan": "Samar",
  "Jiabong": "Samar",
  "Marabut": "Samar",
  "Matuguinao": "Samar",
  "Motiong": "Samar",
  "Pagsanghan": "Samar",
  "Paranas": "Samar",
  "Pinabacdao": "Samar",
  "San Jorge": "Samar",
  "San Jose de Buan": "Samar",
  "San Sebastian": "Samar",
  "Santa Margarita": "Samar",
  "Tagapul-an": "Samar",
  "Talalora": "Samar",
  "Tarangnan": "Samar",
  "Villareal": "Samar",
  "Zumarraga": "Samar",
  "Anahawan": "Southern Leyte",
  "Hinunangan": "Southern Leyte",
  "Hinundayan": "Southern Leyte",
  "Libagon": "Southern Leyte",
  "Limasawa": "Southern Leyte",
  "Macrohon": "Southern Leyte",
  "Malitbog": "Southern Leyte",
  "Pintuyan": "Southern Leyte",
  "Saint Bernard": "Southern Leyte",
  "San Ricardo": "Southern Leyte",
  "Silago": "Southern Leyte",
  "Tomas Oppus": "Southern Leyte",
  "Baliguian": "Zamboanga del Norte",
  "Dapitan": "Zamboanga del Norte",
  "Dipolog": "Zamboanga del Norte",
  "Godod": "Zamboanga del Norte",
  "Gutalac": "Zamboanga del Norte",
  "Jose Dalman": "Zamboanga del Norte",
  "Kalawit": "Zamboanga del Norte",
  "Katipunan": "Zamboanga del Norte",
  "Labason": "Zamboanga del Norte",
  "Leon B. Postigo": "Zamboanga del Norte",
  "Liloy": "Zamboanga del Norte",
  "Manukan": "Zamboanga del Norte",
  "Mutia": "Zamboanga del Norte",
  "Piñan": "Zamboanga del Norte",
  "Polanco": "Zamboanga del Norte",
  "President Manuel A. Roxas": "Zamboanga del Norte",
  "Salug": "Zamboanga del Norte",
  "Sergio Osmeña Sr.": "Zamboanga del Norte",
  "Siayan": "Zamboanga del Norte",
  "Sibuco": "Zamboanga del Norte",
  "Sibutad": "Zamboanga del Norte",
  "Sindangan": "Zamboanga del Norte",
  "Siocon": "Zamboanga del Norte",
  "Sirawai": "Zamboanga del Norte",
  "Tampilisan": "Zamboanga del Norte",
  "Bayog": "Zamboanga del Sur",
  "Dimataling": "Zamboanga del Sur",
  "Dinas": "Zamboanga del Sur",
  "Dumalinao": "Zamboanga del Sur",
  "Dumingag": "Zamboanga del Sur",
  "Guipos": "Zamboanga del Sur",
  "Josefina": "Zamboanga del Sur",
  "Kumalarang": "Zamboanga del Sur",
  "Labangan": "Zamboanga del Sur",
  "Lakewood": "Zamboanga del Sur",
  "Lapuyan": "Zamboanga del Sur",
  "Mahayag": "Zamboanga del Sur",
  "Margosatubig": "Zamboanga del Sur",
  "Midsalip": "Zamboanga del Sur",
  "Molave": "Zamboanga del Sur",
  "Pagadian": "Zamboanga del Sur",
  "Ramon Magsaysay": "Zamboanga del Sur",
  "Sominot": "Zamboanga del Sur",
  "Tabina": "Zamboanga del Sur",
  "Tambulig": "Zamboanga del Sur",
  "Tigbao": "Zamboanga del Sur",
  "Tukuran": "Zamboanga del Sur",
  "Vincenzo A. Sagun": "Zamboanga del Sur",
  "Zamboanga City": "Zamboanga del Sur",
  "Buug": "Zamboanga Sibugay",
  "Diplahan": "Zamboanga Sibugay",
  "Imelda": "Zamboanga Sibugay",
  "Ipil": "Zamboanga Sibugay",
  "Kabasalan": "Zamboanga Sibugay",
  "Mabuhay": "Zamboanga Sibugay",
  "Malangas": "Zamboanga Sibugay",
  "Olutanga": "Zamboanga Sibugay",
  "Payao": "Zamboanga Sibugay",
  "Roseller T. Lim": "Zamboanga Sibugay",
  "Siay": "Zamboanga Sibugay",
  "Talusan": "Zamboanga Sibugay",
  "Titay": "Zamboanga Sibugay",
  "Tungawan": "Zamboanga Sibugay",
  "Baungon": "Bukidnon",
  "Cabanglasan": "Bukidnon",
  "Damulog": "Bukidnon",
  "Dangcagan": "Bukidnon",
  "Don Carlos": "Bukidnon",
  "Impasug-ong": "Bukidnon",
  "Kadingilan": "Bukidnon",
  "Kalilangan": "Bukidnon",
  "Kibawe": "Bukidnon",
  "Kitaotao": "Bukidnon",
  "Lantapan": "Bukidnon",
  "Libona": "Bukidnon",
  "Malaybalay": "Bukidnon",
  "Manolo Fortich": "Bukidnon",
  "Maramag": "Bukidnon",
  "Pangantucan": "Bukidnon",
  "Sumilao": "Bukidnon",
  "Talakag": "Bukidnon",
  "Guinsiliban": "Camiguin",
  "Mahinog": "Camiguin",
  "Mambajao": "Camiguin",
  "Bacolod": "Lanao del Norte",
  "Baloi": "Lanao del Norte",
  "Baroy": "Lanao del Norte",
  "Iligan": "Lanao del Norte",
  "Kapatagan": "Lanao del Norte",
  "Kauswagan": "Lanao del Norte",
  "Kolambugan": "Lanao del Norte",
  "Lala": "Lanao del Norte",
  "Linamon": "Lanao del Norte",
  "Maigo": "Lanao del Norte",
  "Matungao": "Lanao del Norte",
  "Munai": "Lanao del Norte",
  "Nunungan": "Lanao del Norte",
  "Pantao Ragat": "Lanao del Norte",
  "Pantar": "Lanao del Norte",
  "Poona Piagapo": "Lanao del Norte",
  "Salvador": "Lanao del Norte",
  "Sapad": "Lanao del Norte",
  "Sultan Naga Dimaporo": "Lanao del Norte",
  "Tagoloan": "Lanao del Norte",
  "Tangcal": "Lanao del Norte",
  "Tubod": "Lanao del Norte",
  "Aloran": "Misamis Occidental",
  "Baliangao": "Misamis Occidental",
  "Bonifacio": "Misamis Occidental",
  "Don Victoriano Chiongbian": "Misamis Occidental",
  "Jimenez": "Misamis Occidental",
  "Lopez Jaena": "Misamis Occidental",
  "Oroquieta": "Misamis Occidental",
  "Ozamiz": "Misamis Occidental",
  "Panaon": "Misamis Occidental",
  "Sapang Dalaga": "Misamis Occidental",
  "Sinacaban": "Misamis Occidental",
  "Tangub": "Misamis Occidental",
  "Alubijid": "Misamis Oriental",
  "Balingasag": "Misamis Oriental",
  "Balingoan": "Misamis Oriental",
  "Binuangan": "Misamis Oriental",
  "Cagayan de Oro": "Misamis Oriental",
  "El Salvador": "Misamis Oriental",
  "Gingoog": "Misamis Oriental",
  "Gitagum": "Misamis Oriental",
  "Initao": "Misamis Oriental",
  "Jasaan": "Misamis Oriental",
  "Kinoguitan": "Misamis Oriental",
  "Lagonglong": "Misamis Oriental",
  "Lugait": "Misamis Oriental",
  "Manticao": "Misamis Oriental",
  "Medina": "Misamis Oriental",
  "Naawan": "Misamis Oriental",
  "Opol": "Misamis Oriental",
  "Salay": "Misamis Oriental",
  "Sugbongcogon": "Misamis Oriental",
  "Talisayan": "Misamis Oriental",
  "Villanueva": "Misamis Oriental",
  "Laak": "Davao de Oro",
  "Maco": "Davao de Oro",
  "Maragusan": "Davao de Oro",
  "Mawab": "Davao de Oro",
  "Monkayo": "Davao de Oro",
  "Montevista": "Davao de Oro",
  "Nabunturan": "Davao de Oro",
  "New Bataan": "Davao de Oro",
  "Pantukan": "Davao de Oro",
  "Asuncion": "Davao del Norte",
  "Braulio E. Dujali": "Davao del Norte",
  "Kapalong": "Davao del Norte",
  "New Corella": "Davao del Norte",
  "Panabo": "Davao del Norte",
  "Tagum": "Davao del Norte",
  "Talaingod": "Davao del Norte",
  "Bansalan": "Davao del Sur",
  "Davao City": "Davao del Sur",
  "Digos": "Davao del Sur",
  "Kiblawan": "Davao del Sur",
  "Malalag": "Davao del Sur",
  "Matanao": "Davao del Sur",
  "Padada": "Davao del Sur",
  "Sulop": "Davao del Sur",
  "Don Marcelino": "Davao Occidental",
  "Jose Abad Santos": "Davao Occidental",
  "Malita": "Davao Occidental",
  "Sarangani": "Davao Occidental",
  "Baganga": "Davao Oriental",
  "Banaybanay": "Davao Oriental",
  "Boston": "Davao Oriental",
  "Caraga": "Davao Oriental",
  "Cateel": "Davao Oriental",
  "Governor Generoso": "Davao Oriental",
  "Lupon": "Davao Oriental",
  "Manay": "Davao Oriental",
  "Mati": "Davao Oriental",
  "Tarragona": "Davao Oriental",
  "Alamada": "Cotabato",
  "Aleosan": "Cotabato",
  "Antipas": "Cotabato",
  "Arakan": "Cotabato",
  "Banisilan": "Cotabato",
  "Kabacan": "Cotabato",
  "Kidapawan": "Cotabato",
  "Libungan": "Cotabato",
  "Magpet": "Cotabato",
  "Makilala": "Cotabato",
  "Matalam": "Cotabato",
  "Midsayap": "Cotabato",
  "M'lang": "Cotabato",
  "Pigcawayan": "Cotabato",
  "Pikit": "Cotabato",
  "Tulunan": "Cotabato",
  "Alabel": "Sarangani",
  "Glan": "Sarangani",
  "Kiamba": "Sarangani",
  "Maasim": "Sarangani",
  "Maitum": "Sarangani",
  "Malapatan": "Sarangani",
  "Malungon": "Sarangani",
  "General Santos": "South Cotabato",
  "Koronadal": "South Cotabato",
  "Lake Sebu": "South Cotabato",
  "Norala": "South Cotabato",
  "Polomolok": "South Cotabato",
  "Surallah": "South Cotabato",
  "Tampakan": "South Cotabato",
  "Tantangan": "South Cotabato",
  "T'boli": "South Cotabato",
  "Tupi": "South Cotabato",
  "Bagumbayan": "Sultan Kudarat",
  "Columbio": "Sultan Kudarat",
  "Isulan": "Sultan Kudarat",
  "Kalamansig": "Sultan Kudarat",
  "Lambayong": "Sultan Kudarat",
  "Lebak": "Sultan Kudarat",
  "Lutayan": "Sultan Kudarat",
  "Palimbang": "Sultan Kudarat",
  "President Quirino": "Sultan Kudarat",
  "Senator Ninoy Aquino": "Sultan Kudarat",
  "Tacurong": "Sultan Kudarat",
  "Butuan": "Agusan del Norte",
  "Cabadbaran": "Agusan del Norte",
  "Jabonga": "Agusan del Norte",
  "Kitcharao": "Agusan del Norte",
  "Las Nieves": "Agusan del Norte",
  "Nasipit": "Agusan del Norte",
  "Remedios T. Romualdez": "Agusan del Norte",
  "Tubay": "Agusan del Norte",
  "Bayugan": "Agusan del Sur",
  "Bunawan": "Agusan del Sur",
  "Loreto": "Agusan del Sur",
  "Prosperidad": "Agusan del Sur",
  "Santa Josefa": "Agusan del Sur",
  "Sibagat": "Agusan del Sur",
  "Talacogon": "Agusan del Sur",
  "Trento": "Agusan del Sur",
  "Veruela": "Agusan del Sur",
  "Basilisa": "Dinagat Islands",
  "Cagdianao": "Dinagat Islands",
  "Dinagat": "Dinagat Islands",
  "Libjo": "Dinagat Islands",
  "Tubajon": "Dinagat Islands",
  "Bacuag": "Surigao del Norte",
  "Claver": "Surigao del Norte",
  "Dapa": "Surigao del Norte",
  "Del Carmen": "Surigao del Norte",
  "Gigaquit": "Surigao del Norte",
  "Mainit": "Surigao del Norte",
  "Malimono": "Surigao del Norte",
  "San Benito": "Surigao del Norte",
  "Santa Monica": "Surigao del Norte",
  "Surigao City": "Surigao del Norte",
  "Tagana-an": "Surigao del Norte",
  "Barobo": "Surigao del Sur",
  "Bayabas": "Surigao del Sur",
  "Bislig": "Surigao del Sur",
  "Cagwait": "Surigao del Sur",
  "Cantilan": "Surigao del Sur",
  "Carrascal": "Surigao del Sur",
  "Hinatuan": "Surigao del Sur",
  "Lanuza": "Surigao del Sur",
  "Lianga": "Surigao del Sur",
  "Lingig": "Surigao del Sur",
  "Madrid": "Surigao del Sur",
  "Marihatag": "Surigao del Sur",
  "Tagbina": "Surigao del Sur",
  "Tago": "Surigao del Sur",
  "Tandag": "Surigao del Sur",
  "Akbar": "Basilan",
  "Al-Barka": "Basilan",
  "Hadji Mohammad Ajul": "Basilan",
  "Hadji Muhtamad": "Basilan",
  "Lamitan": "Basilan",
  "Lantawan": "Basilan",
  "Maluso": "Basilan",
  "Sumisip": "Basilan",
  "Tipo-Tipo": "Basilan",
  "Ungkaya Pukan": "Basilan",
  "Amai Manabilang": "Lanao del Sur",
  "Bacolod-Kalawi": "Lanao del Sur",
  "Balabagan": "Lanao del Sur",
  "Balindong": "Lanao del Sur",
  "Bayang": "Lanao del Sur",
  "Binidayan": "Lanao del Sur",
  "Buadiposo-Buntong": "Lanao del Sur",
  "Bubong": "Lanao del Sur",
  "Butig": "Lanao del Sur",
  "Calanogas": "Lanao del Sur",
  "Ditsaan-Ramain": "Lanao del Sur",
  "Ganassi": "Lanao del Sur",
  "Kapai": "Lanao del Sur",
  "Lumba-Bayabao": "Lanao del Sur",
  "Lumbaca-Unayan": "Lanao del Sur",
  "Lumbatan": "Lanao del Sur",
  "Lumbayanague": "Lanao del Sur",
  "Madalum": "Lanao del Sur",
  "Madamba": "Lanao del Sur",
  "Maguing": "Lanao del Sur",
  "Malabang": "Lanao del Sur",
  "Marantao": "Lanao del Sur",
  "Marawi": "Lanao del Sur",
  "Marogong": "Lanao del Sur",
  "Masiu": "Lanao del Sur",
  "Mulondo": "Lanao del Sur",
  "Pagayawan": "Lanao del Sur",
  "Piagapo": "Lanao del Sur",
  "Picong": "Lanao del Sur",
  "Poona Bayabao": "Lanao del Sur",
  "Pualas": "Lanao del Sur",
  "Saguiaran": "Lanao del Sur",
  "Sultan Dumalondong": "Lanao del Sur",
  "Tagoloan II": "Lanao del Sur",
  "Tamparan": "Lanao del Sur",
  "Taraka": "Lanao del Sur",
  "Tubaran": "Lanao del Sur",
  "Tugaya": "Lanao del Sur",
  "Wao": "Lanao del Sur",
  "Barira": "Maguindanao del Norte",
  "Buldon": "Maguindanao del Norte",
  "Cotabato City": "Maguindanao del Norte",
  "Datu Blah T. Sinsuat": "Maguindanao del Norte",
  "Datu Odin Sinsuat": "Maguindanao del Norte",
  "Kabuntalan": "Maguindanao del Norte",
  "Matanog": "Maguindanao del Norte",
  "Northern Kabuntalan": "Maguindanao del Norte",
  "Parang": "Maguindanao del Norte",
  "Sultan Kudarat": "Maguindanao del Norte",
  "Sultan Mastura": "Maguindanao del Norte",
  "Upi": "Maguindanao del Norte",
  "Ampatuan": "Maguindanao del Sur",
  "Buluan": "Maguindanao del Sur",
  "Datu Abdullah Sangki": "Maguindanao del Sur",
  "Datu Anggal Midtimbang": "Maguindanao del Sur",
  "Datu Hoffer Ampatuan": "Maguindanao del Sur",
  "Datu Montawal": "Maguindanao del Sur",
  "Datu Paglas": "Maguindanao del Sur",
  "Datu Piang": "Maguindanao del Sur",
  "Datu Salibo": "Maguindanao del Sur",
  "Datu Saudi-Ampatuan": "Maguindanao del Sur",
  "Datu Unsay": "Maguindanao del Sur",
  "General Salipada K. Pendatun": "Maguindanao del Sur",
  "Guindulungan": "Maguindanao del Sur",
  "Mamasapano": "Maguindanao del Sur",
  "Mangudadatu": "Maguindanao del Sur",
  "Pagalungan": "Maguindanao del Sur",
  "Paglat": "Maguindanao del Sur",
  "Pandag": "Maguindanao del Sur",
  "Rajah Buayan": "Maguindanao del Sur",
  "Shariff Aguak": "Maguindanao del Sur",
  "Shariff Saydona Mustapha": "Maguindanao del Sur",
  "South Upi": "Maguindanao del Sur",
  "Sultan sa Barongis": "Maguindanao del Sur",
  "Sultan Sumagka": "Maguindanao del Sur",
  "Talayan": "Maguindanao del Sur",
  "Talitay": "Maguindanao del Sur",
  "Banguingui": "Sulu",
  "Hadji Panglima Tahil": "Sulu",
  "Indanan": "Sulu",
  "Jolo": "Sulu",
  "Kalingalan Caluang": "Sulu",
  "Lugus": "Sulu",
  "Luuk": "Sulu",
  "Maimbung": "Sulu",
  "Old Panamao": "Sulu",
  "Omar": "Sulu",
  "Pandami": "Sulu",
  "Panglima Estino": "Sulu",
  "Pangutaran": "Sulu",
  "Pata": "Sulu",
  "Patikul": "Sulu",
  "Siasi": "Sulu",
  "Talipao": "Sulu",
  "Tapul": "Sulu",
  "Tongkil": "Sulu",
  "Bongao": "Tawi-Tawi",
  "Languyan": "Tawi-Tawi",
  "Mapun": "Tawi-Tawi",
  "Panglima Sugala": "Tawi-Tawi",
  "Sapa-Sapa": "Tawi-Tawi",
  "Sibutu": "Tawi-Tawi",
  "Simunul": "Tawi-Tawi",
  "Sitangkai": "Tawi-Tawi",
  "South Ubian": "Tawi-Tawi",
  "Tandubas": "Tawi-Tawi",
  "Turtle Islands": "Tawi-Tawi"
};

function normPlace(s) {
  return String(s == null ? "" : s)
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const _CITY_INDEX = new Map();
for (const city of Object.keys(CITY_PROVINCE)) _CITY_INDEX.set(normPlace(city), CITY_PROVINCE[city]);

const _PROV_INDEX = new Map();
for (const prov of Object.keys(PROVINCE_CITIES)) {
  _PROV_INDEX.set(normPlace(prov), prov);
  for (const city of PROVINCE_CITIES[prov]) _PROV_INDEX.set(normPlace(city), prov);
}

// The province a city/municipality belongs to, or "" when the table has no
// entry (highly urbanised cities such as Lapu-Lapu and Cebu City are listed
// separately from their province in official tables, so they legitimately miss).
function provinceOfCity(city) {
  return _CITY_INDEX.get(normPlace(city)) || "";
}

function citiesInProvince(province) {
  const real = _PROV_INDEX.get(normPlace(province)) || province;
  const list = PROVINCE_CITIES[real];
  if (!list) return [];
  return list.map(normPlace);
}

// True when `city` is inside `province`. An unknown city returns false: with a
// province requested, an unrecognised location is more likely to be outside the
// area, and assuming it is inside is what produced the wrong-area rows.
function cityInProvince(city, province) {
  if (!province) return true;
  const c = normPlace(city);
  if (!c) return false;
  return citiesInProvince(province).indexOf(c) >= 0;
}

module.exports = { PROVINCE_CITIES, CITY_PROVINCE, normPlace, provinceOfCity, citiesInProvince, cityInProvince };
