"use strict";
/* Regression tests for tools/move_legacy_rules.js.
 *
 * Every one of these guards a bug that actually occurred. The scanner shipped
 * reporting "0 rules" for every input because it walked back over whitespace
 * only, so every one of the 709 selectors extracted as an empty string - a
 * migration tool that silently did nothing. It then treated an @media block as
 * one opaque token, so the 119 rules living inside media queries were invisible,
 * and a rule lifted out of its @media would apply at every width. It also
 * appended a new banner on every run, so repeated migrations stacked duplicate
 * comments.
 *
 * Run: node tests/move_legacy_rules_node.js
 */
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const TOOL = path.join(ROOT, "tools", "move_legacy_rules.js");
let pass = 0, fail = 0;
function chk(name, ok, detail) {
  if (ok) { pass++; console.log("  [PASS] " + name + (detail ? " " + detail : "")); }
  else { fail++; console.log("  [FAIL] " + name + (detail ? " " + detail : "")); }
}

/* Build a throwaway pair of stylesheets and run the tool against them, so the
 * tests never touch the real css/ files. */
function withFixture(legacyCss, storefrontCss, args) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "sflmove_"));
  const cssDir = path.join(dir, "css");
  fs.mkdirSync(cssDir);
  fs.writeFileSync(path.join(cssDir, "storefront-legacy.css"), legacyCss);
  fs.writeFileSync(path.join(cssDir, "storefront.css"), storefrontCss);

  /* The tool resolves ROOT as its own ../ , so run a copy placed one level under
   * a directory that has the fixture in css/. */
  const toolDir = path.join(dir, "tools");
  fs.mkdirSync(toolDir);
  const toolCopy = path.join(toolDir, "move_legacy_rules.js");
  fs.copyFileSync(TOOL, toolCopy);

  let out = "", code = 0;
  try {
    out = execFileSync(process.execPath, [toolCopy].concat(args), { cwd: dir, encoding: "utf8" });
  } catch (e) {
    out = (e.stdout || "") + (e.stderr || "");
    code = e.status === undefined ? -1 : e.status;
  }
  return {
    out: out,
    code: code,
    legacy: fs.readFileSync(path.join(cssDir, "storefront-legacy.css"), "utf8"),
    storefront: fs.readFileSync(path.join(cssDir, "storefront.css"), "utf8"),
    cleanup: function () {
      try { fs.rmSync(dir, { recursive: true, force: true }); } catch (e) { /* noop */ }
    }
  };
}

const BANNER = "/* GENERATED by tools/classify_styles.js --apply  (do not hand-edit)\n *\n */\n\n";

console.log("\n== selectors are extracted, not empty ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n.beta { color: blue; }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--list", "^\\.alpha"]);
  r.cleanup();
  const count = /matching: (\d+)/.exec(r.out);
  chk("--list finds a plain rule", count && Number(count[1]) === 1, "matching=" + (count && count[1]));
  chk("selector text is reported", /\.alpha/.test(r.out));
  chk("no empty selector", !/""|\[\s*\]/.test(r.out.split("matching:")[1] || ""));
}

console.log("\n== the banner comment is not mistaken for a rule ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--list", "GENERATED"]);
  r.cleanup();
  const count = /matching: (\d+)/.exec(r.out);
  chk("file header is not a rule", count && Number(count[1]) === 0, "matching=" + (count && count[1]));
}

console.log("\n== --all-selectors does not lift shared selector-list rules ==");
{
  const legacy = BANNER +
    ".sf-search-form { display: grid; }\n" +
    ".sf-search-form button, .sf-primary-btn { min-height: 48px; }\n" +
    "[data-theme=light] .sf-search-form input, [data-theme=light] .sf-search-form select { color: #111; }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--list", "--all-selectors", "^\\.sf-search-form"]);
  r.cleanup();
  const count = /matching: (\d+)/.exec(r.out);
  chk("pure component rule is selected", count && Number(count[1]) === 1, "matching=" + (count && count[1]));
  chk("mixed shared button rule stays out", !/sf-primary-btn/.test(r.out));
}

console.log("\n== rules inside @media are found and keep their condition ==");
{
  const legacy = BANNER +
    ".alpha { color: red; }\n" +
    "@media (max-width: 760px) {\n" +
    "  .alpha { color: green; }\n" +
    "}\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--list", "^\\.alpha"]);
  r.cleanup();
  const count = /matching: (\d+)/.exec(r.out);
  const cond = /of which inside @media\/@supports: (\d+)/.exec(r.out);
  chk("both the base and the media rule are found", count && Number(count[1]) === 2, "matching=" + (count && count[1]));
  chk("exactly one is conditional", cond && Number(cond[1]) === 1, "conditional=" + (cond && cond[1]));
  chk("the chain is a single level", /\[@media \(max-width: 760px\)\]/.test(r.out), r.out.split("\n").filter(l => l.indexOf("alpha") >= 0).join(" | "));
}

console.log("\n== a moved media rule is re-wrapped, not flattened ==");
{
  const legacy = BANNER +
    ".alpha { color: red; }\n" +
    "@media (max-width: 760px) {\n" +
    "  .alpha { color: green; }\n" +
    "}\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--move", "^\\.alpha"]);
  r.cleanup();
  chk("media condition survives the move", /@media \(max-width: 760px\)/.test(r.storefront));
  chk("the media rule is inside that block",
    /@media \(max-width: 760px\)[\s\S]*?\.alpha \{ color: green/.test(r.storefront));
  chk("the base rule is NOT inside the media block",
    !/@media \(max-width: 760px\)[\s\S]*?\.alpha \{ color: red/.test(r.storefront));
  chk("the media rule is gone from the legacy sheet", !/color: green/.test(r.legacy));
}

console.log("\n== the banner is emitted exactly once across repeated runs ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n.beta { color: blue; }\n";
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "sflmove2_"));
  const cssDir = path.join(dir, "css");
  fs.mkdirSync(cssDir);
  fs.writeFileSync(path.join(cssDir, "storefront-legacy.css"), legacy);
  fs.writeFileSync(path.join(cssDir, "storefront.css"), "/* storefront */\n");
  const toolDir = path.join(dir, "tools");
  fs.mkdirSync(toolDir);
  const toolCopy = path.join(toolDir, "move_legacy_rules.js");
  fs.copyFileSync(TOOL, toolCopy);
  execFileSync(process.execPath, [toolCopy, "--move", "^\\.alpha"], { cwd: dir, encoding: "utf8" });
  execFileSync(process.execPath, [toolCopy, "--move", "^\\.beta"], { cwd: dir, encoding: "utf8" });
  const after = fs.readFileSync(path.join(cssDir, "storefront.css"), "utf8");
  const banners = (after.match(/MIGRATED FROM css\/storefront-legacy\.css/g) || []).length;
  chk("one banner after two migrations", banners === 1, "banners=" + banners);
  chk("both rules are present", /\.alpha/.test(after) && /\.beta/.test(after));
  try { fs.rmSync(dir, { recursive: true, force: true }); } catch (e) { /* noop */ }
}

console.log("\n== braces stay balanced after a move ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n@media (max-width: 760px) { .alpha { color: green; } }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--move", "^\\.alpha"]);
  r.cleanup();
  const open = (r.storefront.match(/\{/g) || []).length;
  const close = (r.storefront.match(/\}/g) || []).length;
  chk("storefront.css balanced", open === close, open + "/" + close);
  const lo = (r.legacy.match(/\{/g) || []).length;
  const lc = (r.legacy.match(/\}/g) || []).length;
  chk("storefront-legacy.css balanced", lo === lc, lo + "/" + lc);
}

console.log("\n== moving nothing is a no-op ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--move", "^\\.nothing_matches"]);
  r.cleanup();
  chk("legacy sheet untouched", r.legacy === legacy);
  chk("no banner added when nothing matched", !/MIGRATED FROM/.test(r.storefront));
}

console.log("\n== dry run writes nothing ==");
{
  const legacy = BANNER + ".alpha { color: red; }\n";
  const r = withFixture(legacy, "/* storefront */\n", ["--move", "--dry-run", "^\\.alpha"]);
  r.cleanup();
  chk("legacy sheet untouched", r.legacy === legacy);
  chk("storefront sheet untouched", r.storefront === "/* storefront */\n");
}

console.log(fail ? "\n" + fail + "/" + (pass + fail) + " FAILED" : "\nALL GREEN (" + pass + " checks)");
process.exit(fail ? 1 : 0);
