"use strict";
const assert = require("assert"), EST = require("../js/estimator.js"), E = require("../js/value_guide_evidence.js"), F = require("../js/value_guide_finance.js");
const config = require("../data/zonal-config.json"), index = require("../data/batangas-zonal.json"), md = require("../data/bir-batangas/municipalities/bauan.json"), registry = require("../data/value-guide-project-evidence.json");
/* Bauan's residential distribution runs p25 1700 / p50 3700 / p75 9000 and the
     fixture street carries 11500/sqm, so it sits ABOVE the municipal median and
     the position-weighted band falls to 1.99 rather than the flat 2.5. That is
     the mechanism: the BIR rate already carries the street's premium, so the
     multiple steps back. Expected figures below are re-derived from the
     DISCLOSED stack rather than frozen, so a weighting change shows as a diff. */
  const base = { municipality: "BAUAN", barangay: "POBLACION III", streetKey: "binay st ressurreccion st", classification: "RR", area: 100, type: "vacant_lot", valuationDate: "2026-10-03", saleContext: "private-resale" };
  const calc = changes => EST.core.computeEstimate(config, index, md, { ...base, ...changes });
  /* One landmark so the many equalities below stay readable, and so a change in
     the band shows up in one place rather than as a wall of diffs. */
  const P = calc();
  const LAND = P.landValue, RATE = P.perSqm;
  let checks = 0;
function check(name, fn) { fn(); checks++; console.log("[PASS] " + name); }
check("the band is weighted down because the street sits above its median", () => { assert.ok(P.bandFlatMid > P.bandMid, "weighted below the flat mid"); assert.ok(P.bandPosition.percentile > 0, "position above the median"); assert.equal(P.birZonalValue, 1150000, "the BIR figure itself never moves"); });
check("Bauan point and approved scenarios remain separate from BIR", () => { assert.equal(P.total, LAND); assert.equal(P.low, Math.round(LAND * 0.85)); assert.equal(P.high, Math.round(LAND * 1.30)); assert.equal(P.birZonalValue, 1150000); });
check("all purposes share the underlying valuation", () => { for (const purpose of config.purposes) assert.equal(calc({ purpose }).total, LAND); });
check("changing area changes total, not necessarily unit rate", () => { const r = calc({ area: 200 }); assert.equal(r.total, LAND * 2); assert.equal(r.perSqm, RATE); });
check("corner applies land-only factor and exposes rate rounding", () => { const r = calc({ corner: true }); assert.ok(r.total > LAND, "a corner lot is worth more"); assert.equal(r.birZonalValue, 1150000); });
check("house floor decimals and depreciation precision retained", () => { const r = calc({ type: "house_lot", floorArea: 63.45 }); assert.equal(r.floorArea, 63.45); assert.equal(r.depreciatedPct, 6.25); assert.equal(r.improvement, Math.round(25000 * 63.45 * .9375)); });
check("building inputs affect intended component monotonically", () => { const h = { type: "house_lot", floorArea: 80 }; assert(calc({ ...h, floorArea: 90 }).improvement > calc(h).improvement); assert(calc({ ...h, construction: "rca_steel" }).improvement > calc(h).improvement); assert(calc({ ...h, ageBand: "21-30" }).improvement < calc(h).improvement); assert(calc({ ...h, floors: "2" }).improvement > calc(h).improvement); });
check("every age band reconciles", () => { for (const age of config.ageBands) { const r = calc({ type: "house_lot", floorArea: 80, ageBand: age.key }); assert.equal(r.improvement, Math.round(25000 * 80 * (1 - age.midpoint / 40))); assert(EST.core.integrityCheck(r).ok); } });
check("all features are charged once", () => { for (const key of Object.keys(config.features)) { const h = calc({ type: "house_lot", floorArea: 80, features: [key, key] }); assert.equal(h.featuresTotal, config.features[key].cost); } });
check("house-only inputs do not change vacant land", () => assert.equal(calc({ floorArea: 90, ageBand: "21-30", features: ["pool"] }).total, P.total));
check("ownership combinations are flags, not arbitrary deductions", () => { for (const occupancy of ["empty", "caretaker", "tenants", "informal_settlers", "not_sure"]) for (const titleStatus of ["titled_self", "titled_previous", "tax_declaration", "not_sure"]) for (const inheritanceStatus of ["not_inherited", "settled", "pending", "not_sure"]) { const r = calc({ occupancy, titleStatus, inheritanceStatus }); assert.equal(r.total, P.total); assert.equal(r.ownershipAdjustmentPct, 0); assert(EST.core.integrityCheck(r).ok); } });
check("site review flags intentionally leave valuation unchanged", () => assert.equal(calc({ floodRisk: "High", roadAccess: "No direct road access", frontage: "Narrow" }).total, P.total));
check("invalid inputs fail explicitly", () => { for (const changes of [{ area: Infinity }, { area: 19 }, { area: 100001 }, { salePrice: -1 }, { salePrice: Infinity }, { type: "other" }, { type: "house_lot", floorArea: -1 }, { type: "house_lot", construction: "other" }, { type: "house_lot", ageBand: "other" }, { type: "house_lot", floors: 9 }, { type: "house_lot", features: ["unknown"] }, { titleStatus: "unknown-invalid" }]) assert.equal(calc(changes).available, false, JSON.stringify(changes)); });
check("numeric storeys canonicalize to supported string key", () => assert.equal(calc({ type: "house_lot", floorArea: 80, floors: 2 }).floorsMultiplier, 1.05));
check("sale and offer scenarios change costs, not valuation", () => { const r = calc({ salePrice: 3000000 }); assert.equal(r.total, P.total); const c = EST.core.costsFor(r, config); assert.equal(c.projectedNetProceeds, 2730000); assert.equal(c.buyerTotal, 3063000); });
check("tax floor can legitimately plateau", () => { const a = EST.core.costsFor(calc({ salePrice: 900000 }), config), b = EST.core.costsFor(calc({ salePrice: 1000000 }), config); assert.equal(a.cgt, 69000); assert.equal(a.cgt, b.cgt); assert.notEqual(a.projectedNetProceeds, b.projectedNetProceeds); });
check("derived median is never a confirmed parcel tax floor", () => { const r = calc({ barangay: "UNKNOWN", streetKey: "", salePrice: 100000 }); assert(r.source.depth >= 3); assert.equal(r.birReferenceConfirmed, false); assert.equal(r.taxReferenceValue, 0); assert.equal(EST.core.costsFor(r, config).base, 100000); });
check("developer costs require quote and never double-charge taxes", () => { const r = calc({ saleContext: "developer", salePrice: 3000000 }); const c = EST.core.costsFor(r, config); assert.equal(c.cgt, null); assert.equal(c.buyerTotal, null); const quote = EST.core.costsFor(calc({ saleContext: "developer", salePrice: 3000000, developerFees: 100000 }), config); assert.equal(quote.buyerTotal, 3100000); assert.equal(quote.total, 100000); });
check("negotiated allocation and commission remain separate", () => { const c = F.transaction({}, 3000000, { salePrice: 3000000, brokerPct: .02, costAllocation: { broker: "buyer" } }); assert.equal(c.sellerCosts, 180000); assert.equal(c.buyerCosts, 123000); });
check("catalog sqm and precomputed-rate input normalize consistently", () => { const r = E.normalize({ city: "Bauan", property_type: "lot-only", price: 3000000, lot_area_sqm: 100, pricePerSqm: 999999 }); assert.equal(r.pricePerSqm, 30000); assert.equal(E.normalize({ pricePerSqm: 999999, city: "Bauan" }), null); });
check("transaction label alone does not establish verified sale", () => assert(E.normalize({ price: 1e6, lotArea: 100 }, "SEA ESTATES transaction").isAskingPrice));
const records = [2000000, 3000000, 4000000].map((price, i) => ({ id: "parcel-" + i, propertyIdentity: "Parcel " + i, sourceUrl: "https://example.test/parcel-" + i, municipality: "Bauan", barangay: "Poblacion III", province: "Batangas", propertyType: "lot-only", lotArea: 100, price, priceAsOf: "2026-10-02", saleContext: "private-resale", useGroup: "residential", corner: false }));
check("qualified asking indication is separate, not BIR-blended", () => { const r = calc({ comparables: records }); assert.equal(r.askingIndication.value, 3000000); assert.equal(r.askingIndication.count, 3); assert.equal(r.askingIndication.low, 2000000); assert.equal(r.total, P.total); });
check("duplicates do not create evidence sufficiency", () => assert.equal(calc({ comparables: [records[0], records[0], records[0]] }).askingIndication, null));
check("known risk cannot borrow ordinary-property asking indication", () => { const r = calc({ comparables: records, floodRisk: "High" }); assert.equal(r.askingIndication, null); assert.equal(r.total, P.total); assert.equal(r.siteReview.floodRisk, "High"); });
check("missing/future/stale dates prevent numerical use", () => { for (const priceAsOf of [null, "2027-01-01", "2020-01-01", "2026-02-30"]) assert.equal(calc({ comparables: records.map(r => ({ ...r, priceAsOf })) }).askingIndication, null); });
check("membership, sample, missing use and wrong type excluded", () => { for (const changes of [{ includesMembership: true }, { synthetic: true }, { priceRange: [1, 2] }, { useGroup: "" }, { propertyType: "house-and-lot" }]) assert.equal(calc({ comparables: records.map(r => ({ ...r, ...changes })) }).askingIndication, null); });
check("house package indication never adds building cost again", () => { const houseRows = records.map((r, i) => ({ ...r, price: (i + 5) * 1e6, propertyType: "house-and-lot", floorArea: 90, areaBasis: "gross-floor", condition: "new" })); const r = calc({ type: "house_lot", floorArea: 90, condition: "new", comparables: houseRows }); assert.equal(r.askingIndication.value, 6000000); assert.notEqual(r.askingIndication.value, 6000000 + r.improvement); });
check("even-sized median uses both middle observations", () => assert.equal(E.median([20000, 30000]), 25000));
check("researched project records remain ineligible for numerical model", () => { assert.equal(registry.records.length, 17); for (const r of registry.records) assert.equal(r.numericalAllowed, false); for (const municipality of ["LIPA CITY", "BAUAN", "SAN PASCUAL", "BATANGAS CITY", "ALITAGTAG"]) assert.equal(calc({ comparables: registry.records, municipality }).askingIndication || null, null); });
console.log("ALL GREEN (" + checks + " checks; 80 ownership combinations plus input matrix)");
